# -*- coding: utf-8 -*-
"""
Script to generate 300 high-quality standard multiple choice questions for IT Fundamentals (CNTT Cơ bản)
Organized into 6 modules (50 questions each = 300 questions)
"""

import json

modules_info = {
    1: "Module 1: Hiểu biết về CNTT cơ bản (IU01)",
    2: "Module 2: Sử dụng máy tính cơ bản (IU02)",
    3: "Module 3: Xử lý văn bản cơ bản - MS Word (IU03)",
    4: "Module 4: Sử dụng bảng tính cơ bản - MS Excel (IU04)",
    5: "Module 5: Sử dụng trình chiếu cơ bản - MS PowerPoint (IU05)",
    6: "Module 6: Sử dụng Internet cơ bản (IU06)",
}

questions = []

# Module 1: Hiểu biết về CNTT cơ bản (IU01) - 50 questions
m1_data = [
    ("Thiết bị nào sau đây là thiết bị ngoại vi dùng để nhập dữ liệu vào máy tính?",
     ["Bàn phím (Keyboard)", "Màn hình (Monitor)", "Máy in (Printer)", "Loa (Speaker)"], 0,
     "Bàn phím là thiết bị đầu vào (Input device) để người dùng nhập văn bản và lệnh."),
    ("Đơn vị đo dung lượng thông tin cơ bản nhỏ nhất trong máy tính là gì?",
     ["Bit", "Byte", "Kilobyte (KB)", "Megabyte (MB)"], 0,
     "Bit (Binary Digit) là đơn vị đo thông tin nhỏ nhất, chỉ nhận giá trị 0 hoặc 1."),
    ("1 Byte bằng bao nhiêu Bit?",
     ["8 Bit", "16 Bit", "1024 Bit", "2 Bit"], 0,
     "1 Byte = 8 bits theo quy ước chuẩn của khoa học máy tính."),
    ("1 Kilobyte (KB) theo hệ thống nhị phân tương đương với bao nhiêu Byte?",
     ["1024 Byte", "1000 Byte", "1048576 Byte", "512 Byte"], 0,
     "1 KB = 2^10 = 1024 Bytes."),
    ("Thiết bị nào được ví như 'bộ não' của máy tính, thực hiện các phép tính và điều khiển toàn bộ hệ thống?",
     ["CPU (Central Processing Unit)", "RAM (Random Access Memory)", "Ổ đĩa cứng (Hard Disk Drive)", "Bộ nguồn (Power Supply)"], 0,
     "CPU (bộ vi xử lý trung tâm) là cơ quan đầu não xử lý và điều hành máy tính."),
    ("RAM trong máy tính có đặc điểm nào nổi bật nhất?",
     ["Dữ liệu bị mất đi khi mất nguồn điện (Bộ nhớ khả biến)", "Dữ liệu được lưu trữ vĩnh viễn không mất đi", "Chỉ đọc dữ liệu chứ không ghi được", "Dùng để sao lưu dữ liệu lâu dài"], 0,
     "RAM là bộ nhớ truy xuất ngẫu nhiên khả biến (Volatile Memory), mất dữ liệu khi tắt nguồn."),
    ("ROM (Read Only Memory) có chức năng chính là gì?",
     ["Lưu trữ các chương trình khởi động cơ bản của hệ thống (BIOS/UEFI)", "Lưu trữ tạm dữ liệu đang xử lý của người dùng", "Tăng tốc độ xử lý đồ họa máy tính", "Lưu trữ file tài liệu của người dùng"], 0,
     "ROM chứa mã lệnh cơ bản để khởi động phần cứng và kiểm tra hệ thống ban đầu."),
    ("Phần mềm nào sau đây là phần mềm hệ thống (System Software)?",
     ["Hệ điều hành Windows 11", "Microsoft Office Word", "Trình duyệt Google Chrome", "Phần mềm đồ họa Adobe Photoshop"], 0,
     "Hệ điều hành (Windows, Linux, macOS) là phần mềm hệ thống điều khiển phần cứng."),
    ("Thuật ngữ 'Open Source Software' (Phần mềm mã nguồn mở) có nghĩa là gì?",
     ["Phần mềm được công khai mã nguồn và cho phép người dùng tự do sửa đổi, phân phối", "Phần mềm miễn phí nhưng không được xem mã nguồn", "Phần mềm dùng thử có thời hạn", "Phần mềm bắt buộc phải trả phí bản quyền hàng tháng"], 0,
     "Phần mềm nguồn mở (như Linux, LibreOffice) cung cấp mã nguồn tự do."),
    ("Thiết bị nào sau đây là thiết bị xuất (Output device)?",
     ["Máy in (Printer)", "Chuột máy tính (Mouse)", "Máy quét (Scanner)", "Microphone"], 0,
     "Máy in xuất dữ liệu ra trang giấy nên là thiết bị đầu ra."),
    ("Tốc độ xử lý của CPU thường được đo bằng đơn vị nào hiện nay?",
     ["GHz (Gigahertz)", "GB (Gigabyte)", "Gbps (Gigabit per second)", "RPM (Vòng trên phút)"], 0,
     "Tần số xung nhịp của CPU hiện nay được đo bằng GHz hoặc MHz."),
    ("Cổng kết nối HDMI trên máy tính thường dùng để truyền tải tín hiệu gì?",
     ["Cả hình ảnh độ nét cao và âm thanh", "Chỉ truyền tín hiệu âm thanh", "Chỉ truyền tín hiệu hình ảnh", "Truyền tải nguồn điện sạc công suất lớn"], 0,
     "HDMI (High-Definition Multimedia Interface) truyền đồng thời cả video và audio chất lượng cao."),
    ("Hành vi nào sau đây vi phạm luật bản quyền phần mềm?",
     ["Bẻ khóa (Crack) và sử dụng phần mềm thương mại khi chưa mua bản quyền", "Tải và cài đặt phần mềm mã nguồn mở", "Mua bản quyền phần mềm chính hãng để sử dụng", "Sử dụng các phần mềm được cung cấp miễn phí (Freeware)"], 0,
     "Việc bẻ khóa và dùng phần mềm không bản quyền là hành vi vi phạm pháp luật."),
    ("Mã độc (Malware) nào có khả năng tự nhân bản và lây lan qua mạng hoặc thiết bị lưu trữ?",
     ["Virus / Worm máy tính", "Firewall (Tường lửa)", "Ứng dụng diệt virus", "Driver máy in"], 0,
     "Virus và Worm là các chương trình mã độc có khả năng tự sao chép và phát tán."),
    ("Trojan Horse trong bảo mật máy tính là gì?",
     ["Chương trình độc hại ngụy trang dưới dạng phần mềm hữu ích hợp pháp", "Phần mềm chống virus chính hãng", "Phần cứng dùng để lọc dữ liệu mạng", "Hệ điều hành dành riêng cho máy chủ"], 0,
     "Trojan ngụy trang thành phần mềm vô hại để đánh lừa người dùng cài đặt."),
    ("Ransomware là loại mã độc nguy hiểm thực hiện hành vi nào sau đây?",
     ["Mã hóa dữ liệu của nạn nhân và đòi tiền chuộc để giải mã", "Xóa sạch hệ điều hành ngay lập tức", "Làm hỏng hoàn toàn phần cứng CPU", "Tự động tắt máy tính sau mỗi 10 phút"], 0,
     "Ransomware là mã độc tống tiền bằng cách mã hóa các tập tin quan trọng."),
    ("Biện pháp nào sau đây giúp bảo vệ tài khoản người dùng trực tuyến an toàn nhất?",
     ["Kích hoạt xác thực 2 yếu tố (2FA / Two-factor authentication)", "Đặt mật khẩu dễ nhớ như ngày sinh nhật", "Sử dụng chung một mật khẩu cho tất cả tài khoản", "Lưu mật khẩu vào file word để ở màn hình desktop"], 0,
     "Xác thực 2 yếu tố (2FA) bổ sung lớp bảo vệ phụ ngăn chặn truy cập trái phép."),
    ("Mật khẩu nào sau đây được xem là có độ an toàn và mạnh nhất?",
     ["P@ssw0rd#2026", "12345678", "admin123", "password"], 0,
     "Mật khẩu mạnh kết hợp chữ hoa, chữ thường, chữ số và ký tự đặc biệt."),
    ("Công thái học (Ergonomics) trong sử dụng máy tính khuyến nghị điều gì?",
     ["Màn hình ngang tầm mắt, ngồi thẳng lưng, nghỉ ngơi sau mỗi 45-60 phút", "Ngồi thật sát màn hình để nhìn rõ chữ nhỏ", "Làm việc liên tục 8 tiếng không rời ghế để tăng năng suất", "Đặt bàn phím càng cao hơn vai càng tốt"], 0,
     "Tư thế chuẩn giúp phòng tránh thoái hóa cột sống và mỏi mắt."),
    ("Thiết bị nào sau đây dùng để lưu trữ dữ liệu lâu dài và không bị mất khi tắt nguồn?",
     ["Ổ đĩa SSD / HDD", "Bộ nhớ RAM", "Bộ nhớ Cache L1 của CPU", "Thanh ghi Registers"], 0,
     "SSD/HDD là bộ nhớ ngoài không khả biến dùng lưu trữ dữ liệu vĩnh viễn."),
    ("Chuột máy tính thông thường gồm có các nút bấm chính nào?",
     ["Nút trái, nút phải và bánh xe cuộn (Scroll wheel)", "Chỉ có nút trái", "Chỉ có nút cuộn", "Nút nguồn và nút âm lượng"], 0,
     "Chuột chuẩn có chuột trái (chọn/mở), chuột phải (menu ngữ cảnh) và nút cuộn."),
    ("Một người bị đau cổ tay khi sử dụng chuột liên tục nên áp dụng biện pháp nào?",
     ["Sử dụng miếng lót chuột có đệm đỡ cổ tay và chuột công thái học", "Tăng tốc độ di chuyển chuột lên tối đa", "Dùng tay còn lại đè mạnh lên cổ tay", "Không cử động tay trong nhiều giờ"], 0,
     "Đệm cổ tay giúp giữ cổ tay ở góc thẳng tự nhiên, giảm áp lực lên ống cổ tay."),
    ("Để tiết kiệm điện năng và bảo vệ môi trường, khi không dùng máy tính trong thời gian dài bạn nên làm gì?",
     ["Tắt máy (Shut down) và rút phích cắm hoặc ngắt nguồn", "Bật màn hình chờ Screen Saver với hiệu ứng 3D", "Để máy tính chạy không tải suốt đêm", "Bật quạt gió thổi vào màn hình"], 0,
     "Tắt hoàn toàn nguồn giúp tiết kiệm điện và giảm nguy cơ chập cháy."),
    ("Hệ thống số nhị phân (Binary) mà máy tính sử dụng chỉ gồm hai chữ số nào?",
     ["0 và 1", "0 và 2", "1 và 2", "1 và 10"], 0,
     "Nhị phân sử dụng cơ số 2 với hai ký hiệu 0 và 1."),
    ("Hệ điều hành mã nguồn mở phổ biến nhất trên thế giới hiện nay là gì?",
     ["Linux (Ubuntu, Debian, Fedora...)", "Microsoft Windows", "Apple macOS", "Apple iOS"], 0,
     "Linux là nhân hệ điều hành mã nguồn mở phổ biến nhất."),
    ("Chương trình gián điệp (Spyware) có mục đích chính là gì?",
     ["Âm thầm theo dõi và thu thập thông tin cá nhân của người dùng gửi về máy chủ kẻ tấn công", "Tăng tốc độ truy cập internet của máy tính", "Dọn dẹp rác hệ thống tự động", "Bảo vệ máy tính khỏi sâu mạng"], 0,
     "Spyware hoạt động ngầm để đánh cắp mật khẩu, lịch sử duyệt web và thông tin nhạy cảm."),
    ("Để tránh nguy cơ mất mát dữ liệu do hỏng ổ cứng hoặc nhiễm virus, người dùng nên thực hiện việc gì định kỳ?",
     ["Sao lưu dự phòng dữ liệu (Backup) sang ổ cứng ngoài hoặc đám mây", "Đổi tên file liên tục", "Chống phân mảnh ổ cứng mỗi giờ một lần", "Nâng cấp card âm thanh"], 0,
     "Sao lưu (Backup) là giải pháp an toàn hàng đầu để phòng chống mất dữ liệu."),
    ("Địa chỉ IP (Internet Protocol) trên thiết bị dùng để làm gì?",
     ["Định danh duy nhất một thiết bị khi tham gia kết nối mạng", "Đo tốc độ xử lý của CPU máy tính", "Xác định mã số của bộ nhớ RAM", "Lưu trữ hệ điều hành"], 0,
     "Địa chỉ IP là địa chỉ logic định danh thiết bị trên mạng máy tính."),
    ("Tường lửa (Firewall) trong máy tính có tác dụng gì?",
     ["Kiểm soát và ngăn chặn các kết nối mạng trái phép hoặc nguy hiểm", "Dập tắt hỏa hoạn khi máy tính quá nóng", "Tăng dung lượng lưu trữ của ổ cứng", "Sửa chữa các lỗi phần cứng bị hỏng"], 0,
     "Firewall là rào chắn an ninh lọc các gói tin mạng ra vào hệ thống."),
    ("Thiết bị nào sau đây vừa là thiết bị nhập vừa là thiết bị xuất dữ liệu?",
     ["Màn hình cảm ứng (Touchscreen)", "Máy in laser đen trắng", "Bàn phím cơ", "Loa vi tính 2.1"], 0,
     "Màn hình cảm ứng vừa hiển thị (xuất) vừa nhận thao tác chạm ngón tay (nhập)."),
    ("Công nghệ lưu trữ 'Cloud Storage' (Lưu trữ đám mây) có ưu điểm nào sau đây?",
     ["Có thể truy cập dữ liệu mọi lúc, mọi nơi thông qua kết nối Internet", "Không cần kết nối mạng vẫn truy cập được dữ liệu từ xa", "Hoàn toàn miễn phí không giới hạn dung lượng với tất cả nhà cung cấp", "Không bao giờ bị ảnh hưởng bởi lỗi mạng"], 0,
     "Lưu trữ đám mây cho phép đồng bộ và chia sẻ dữ liệu thuận tiện qua Internet."),
    ("Bản quyền tác giả (Copyright) phần mềm bảo vệ quyền lợi nào của tác giả?",
     ["Quyền sở hữu trí tuệ và quyền phân phối sản phẩm", "Quyền được sử dụng miễn phí mọi phần cứng", "Quyền miễn trừ mọi trách nhiệm pháp lý", "Quyền thu hồi máy tính của khách hàng bất kỳ lúc nào"], 0,
     "Bản quyền bảo hộ quyền tác giả và quyền liên quan theo luật sở hữu trí tuệ."),
    ("Thuật ngữ 'Phishing' (Tấn công giả mạo) trong an ninh mạng là gì?",
     ["Hình thức lừa đảo giả danh ngân hàng/dịch vụ uy tín để chiếm đoạt thông tin đăng nhập", "Một trò chơi câu cá giải trí trên mạng", "Kỹ thuật nâng cao tốc độ tải trang web", "Phương thức kết nối mạng không dây an toàn"], 0,
     "Phishing là hình thức gửi email/web giả mạo để lừa người dùng nhập tài khoản, mật khẩu."),
    ("Một terabyte (1 TB) bằng khoảng bao nhiêu Gigabyte (GB)?",
     ["1024 GB", "100 GB", "10000 GB", "512 GB"], 0,
     "1 TB = 1024 GB theo quy ước nhị phân."),
    ("Thiết bị UPS (Uninterruptible Power Supply) có chức năng gì cho máy tính?",
     ["Cung cấp nguồn điện tạm thời khi điện lưới bị mất để kịp lưu dữ liệu và tắt máy an toàn", "Tăng tốc độ vi xử lý CPU", "Thay thế ổ đĩa cứng khi bị đầy", "Lọc virus trong nguồn điện"], 0,
     "Bộ lưu điện (UPS) duy trì dòng điện tạm thời giúp bảo vệ dữ liệu khi mất điện đột ngột."),
    ("Việc tái chế rác thải điện tử (E-waste) đúng cách mang lại lợi ích gì?",
     ["Bảo vệ môi trường và thu hồi các kim loại quý hiếm", "Làm cho máy tính mới chạy nhanh gấp đôi", "Tạo ra virus máy tính mới", "Tăng chi phí sản xuất năng lượng toàn cầu"], 0,
     "Rác thải điện tử chứa nhiều chất độc hại cần được xử lý và tái chế an toàn."),
    ("Phần mềm chia sẻ miễn phí có giới hạn tính năng hoặc thời gian sử dụng được gọi là gì?",
     ["Shareware (Phần mềm dùng thử)", "Freeware", "Open source software", "Firmware"], 0,
     "Shareware cho phép dùng thử một khoảng thời gian trước khi yêu cầu mua bản quyền."),
    ("Tệp tin có phần mở rộng .EXE trên hệ điều hành Windows đại diện cho loại tệp tin nào?",
     ["Tệp tin chương trình thực thi (Executable file)", "Tệp tin hình ảnh đồ họa", "Tệp tin âm thanh bài hát", "Tệp tin văn bản Word"], 0,
     ".exe là định dạng file chương trình có thể chạy trực tiếp trên Windows."),
    ("Phần mềm độc hại 'Keylogger' thực hiện hành vi nào?",
     ["Ghi lại mọi thao tác gõ phím của người dùng nhằm đánh cắp mật khẩu", "Tự động khóa bàn phím không cho người dùng gõ", "Xóa toàn bộ các phím tắt trong Windows", "Tự động sửa lỗi chính tả khi gõ văn bản"], 0,
     "Keylogger bí mật thu thập chuỗi phím bấm để trộm thông tin tài khoản và thẻ tín dụng."),
    ("Khi làm việc với máy tính, khoảng cách an toàn từ mắt đến màn hình được khuyến nghị là bao nhiêu?",
     ["Khoảng 50 cm đến 70 cm (tầm một sải cánh tay)", "Dưới 20 cm", "Khoảng 2 mét", "Càng sát màn hình càng tốt"], 0,
     "Khoảng cách 50-70cm giúp mắt không bị điều tiết quá mức và tránh mỏi mắt."),
    ("SSD (Solid State Drive) có ưu thế vượt trội nào so với HDD truyền thống?",
     ["Tốc độ đọc/ghi dữ liệu nhanh hơn nhiều và chống sốc tốt hơn", "Dung lượng luôn gấp 10 lần HDD với cùng mức giá", "Không bao giờ bị lỗi phần mềm", "Sử dụng đĩa quay cơ học với tốc độ cao hơn"], 0,
     "SSD sử dụng bộ nhớ flash bán dẫn, không dùng cơ đĩa quay nên tốc độ rất cao và bền bỉ."),
    ("Hệ quản trị cơ sở dữ liệu (DBMS) nào sau đây là phổ biến trong tin học?",
     ["Microsoft Access / SQL Server", "Microsoft Paint", "Windows Media Player", "Notepad"], 0,
     "Access và SQL Server là các hệ quản trị cơ sở dữ liệu chuyên dụng."),
    ("Để bảo vệ mắt khi làm việc buổi tối trên máy tính, tính năng nào thường được kích hoạt?",
     ["Night Light (Chế độ lọc ánh sáng xanh)", "Tăng độ sáng màn hình lên 100%", "Chế độ tương phản cao trắng đen", "Chuyển màn hình sang độ phân giải thấp"], 0,
     "Ánh sáng vàng ấm của Night light giảm tác hại của ánh sáng xanh đến giấc ngủ."),
    ("Tên viết tắt của mạng cục bộ trong phạm vi một văn phòng hoặc tòa nhà là gì?",
     ["LAN (Local Area Network)", "WAN (Wide Area Network)", "MAN (Metropolitan Area Network)", "PAN (Personal Area Network)"], 0,
     "LAN là mạng kết nối các máy tính trong phạm vi hẹp như trường học, công ty."),
    ("Thiết bị nào sau đây dùng để chuyển đổi tín hiệu số thành tín hiệu tương tự và ngược lại để truyền dữ liệu qua đường truyền?",
     ["Modem", "Bàn phím", "Màn hình", "Ổ đĩa quang CD-ROM"], 0,
     "Modem (Modulator-Demodulator) có nhiệm vụ điều chế và giải điều chế tín hiệu."),
    ("Chương trình BIOS được cài đặt sẵn trên linh kiện nào của máy tính?",
     ["Chip ROM trên bo mạch chủ (Motherboard)", "Trên thanh RAM", "Trên đĩa cứng HDD", "Trên card màn hình rời"], 0,
     "BIOS được nạp sẵn vào chip ROM CMOS trên Mainboard."),
    ("Hành vi 'Spam' qua hòm thư điện tử là gì?",
     ["Gửi thư rác hàng loạt với nội dung quảng cáo hoặc lừa đảo mà người nhận không mong muốn", "Gửi thư chúc mừng sinh nhật người thân", "Chia sẻ tài liệu công việc cho đồng nghiệp", "Nhận thông báo cập nhật hệ thống từ nhà sản xuất"], 0,
     "Spam mail là thư rác được gửi đồng loạt tới nhiều địa chỉ mà không được sự đồng ý."),
    ("Chứng chỉ SSL/TLS trên website an toàn được biểu thị bằng dấu hiệu nào trên thanh địa chỉ trình duyệt?",
     ["Biểu tượng ổ khóa và tiền tố https://", "Biểu tượng dấu chấm than màu đỏ", "Chữ http:// gạch ngang", "Biểu tượng chiếc chìa khóa bị gãy"], 0,
     "HTTPS và biểu tượng ổ khóa chứng minh kết nối giữa trình duyệt và máy chủ được mã hóa an toàn."),
    ("Chức năng của cổng kết nối USB (Universal Serial Bus) là gì?",
     ["Cung cấp chuẩn kết nối đa năng cho phép truyền dữ liệu và cấp nguồn cho thiết bị ngoại vi", "Chỉ dùng để kết nối mạng Internet qua dây cáp", "Chỉ dùng để xuất âm thanh nổi 5.1", "Chỉ dùng để cắm thẻ nhớ máy ảnh"], 0,
     "USB là chuẩn kết nối đa năng thông dụng nhất cho chuột, phím, USB flash, máy in..."),
    ("Bạn nhận được một bức thư điện tử chứa tệp tin đính kèm mà bạn không nhận biết ra. Những bước hành động tốt nhất nào bạn sẽ thực hiện từ khía cạnh an ninh?",
     ["Quét tập tin này bằng chương trình chống virus hoặc không mở tệp tin khả nghi", "Chuyển thư này cho ai đó mà bạn nghĩ rằng bạn có thể nhận biết được", "Mở tệp tin này ra để kiểm tra loại tệp tin", "Lưu bản sao tập tin này vào đĩa cứng và mở bản sao này"], 0,
     "Để đảm bảo an toàn, không mở tệp tin lạ và cần quét virus hoặc xóa bỏ thư khả nghi.")
]

for q_text, opts, ans, exp in m1_data:
    questions.append({
        "id": len(questions) + 1,
        "module": 1,
        "moduleName": modules_info[1],
        "question": q_text,
        "options": opts,
        "answer": ans,
        "explanation": exp
    })

# Module 2: Sử dụng máy tính cơ bản (IU02) - 50 questions
m2_data = [
    ("Trong hệ điều hành Windows, tổ hợp phím nào sau đây dùng để sao chép (Copy) đối tượng đang chọn?",
     ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"], 0,
     "Ctrl + C là phím tắt tiêu chuẩn để sao chép dữ liệu vào Clipboard."),
    ("Tổ hợp phím tắt nào dùng để dán (Paste) dữ liệu từ Clipboard?",
     ["Ctrl + V", "Ctrl + C", "Ctrl + P", "Ctrl + S"], 0,
     "Ctrl + V dùng để dán nội dung đã sao chép hoặc cắt."),
    ("Tổ hợp phím tắt nào dùng để cắt (Cut) một đối tượng được chọn?",
     ["Ctrl + X", "Ctrl + C", "Ctrl + Z", "Ctrl + A"], 0,
     "Ctrl + X thực hiện thao tác cắt đối tượng đưa vào bộ nhớ tạm."),
    ("Tổ hợp phím nào dùng để hoàn tác (Undo) lại thao tác vừa thực hiện?",
     ["Ctrl + Z", "Ctrl + Y", "Ctrl + U", "Ctrl + W"], 0,
     "Ctrl + Z dùng để quay lui (Undo) thao tác vừa làm trước đó."),
    ("Để chọn toàn bộ các tệp tin và thư mục trong cửa sổ hiện hành, bạn nhấn tổ hợp phím nào?",
     ["Ctrl + A", "Ctrl + S", "Alt + A", "Shift + A"], 0,
     "Ctrl + A (Select All) dùng để bôi đen/chọn toàn bộ đối tượng."),
    ("Phím chức năng nào trên bàn phím dùng để đổi tên (Rename) tệp hoặc thư mục đang chọn trong Windows?",
     ["F2", "F1", "F5", "F12"], 0,
     "F2 là phím tắt đổi tên tập tin hoặc thư mục được chọn."),
    ("Phím nào dùng để làm mới (Refresh) lại nội dung cửa sổ hoặc trang web hiện hành?",
     ["F5", "F3", "F7", "F11"], 0,
     "F5 giúp tải lại / làm mới màn hình hoặc trang web."),
    ("Thao tác xóa tệp tin bằng phím Delete thông thường thì tệp tin sẽ được chuyển vào đâu?",
     ["Thùng rác Recycle Bin", "Xóa vĩnh viễn khỏi ổ cứng ngay lập tức", "Chuyển vào thư mục Documents", "Được ẩn đi trong thư mục gốc"], 0,
     "Khi bấm phím Delete, file được chuyển tạm vào Recycle Bin để có thể khôi phục khi cần."),
    ("Để xóa vĩnh viễn một tệp tin mà không đưa vào Recycle Bin, bạn sử dụng tổ hợp phím nào?",
     ["Shift + Delete", "Ctrl + Delete", "Alt + Delete", "Ctrl + Shift + Delete"], 0,
     "Shift + Delete sẽ xóa trực tiếp file ra khỏi ổ đĩa mà không lưu vào thùng rác."),
    ("Để mở trình quản lý tệp tin File Explorer trong Windows một cách nhanh nhất, ta dùng tổ hợp phím:",
     ["Windows + E", "Windows + R", "Windows + D", "Windows + L"], 0,
     "Windows + E (Explorer) mở nhanh cửa sổ File Explorer."),
    ("Tổ hợp phím Windows + D có tác dụng gì trong hệ điều hành Windows?",
     ["Thu nhỏ tất cả cửa sổ và hiển thị màn hình nền Desktop", "Mở hộp thoại Run", "Khóa màn hình máy tính", "Mở trình duyệt web mặc định"], 0,
     "Windows + D (Desktop) ẩn/hiện màn hình chính Desktop tức thì."),
    ("Để khóa máy tính nhanh khi bạn rời khỏi bàn làm việc, bạn nên nhấn tổ hợp phím nào?",
     ["Windows + L", "Windows + K", "Ctrl + Alt + L", "Alt + F4"], 0,
     "Windows + L (Lock) khóa màn hình máy tính ngay lập tức."),
    ("Hộp thoại 'Run' trong Windows được kích hoạt bằng tổ hợp phím nào?",
     ["Windows + R", "Windows + F", "Ctrl + R", "Alt + R"], 0,
     "Windows + R (Run) mở hộp thoại thực thi lệnh nhanh."),
    ("Tổ hợp phím nào dùng để đóng cửa sổ chương trình đang kích hoạt hoặc tắt máy tính?",
     ["Alt + F4", "Ctrl + F4", "Shift + F4", "Windows + F4"], 0,
     "Alt + F4 đóng cửa sổ hiện hành hoặc mở menu tắt máy khi ở màn hình nền."),
    ("Để chuyển đổi qua lại nhanh giữa các cửa sổ ứng dụng đang mở, bạn sử dụng tổ hợp phím nào?",
     ["Alt + Tab", "Ctrl + Tab", "Shift + Tab", "Windows + Tab"], 0,
     "Alt + Tab cho phép chuyển nhanh giữa các cửa sổ tác vụ."),
    ("Công cụ nào trong Windows dùng để gỡ cài đặt phần mềm và quản lý các thiết lập hệ thống?",
     ["Control Panel / Settings", "Task Manager", "Recycle Bin", "Command Prompt"], 0,
     "Control Panel hoặc Windows Settings quản lý cấu hình và gỡ bỏ phần mềm."),
    ("Để xem và quản lý các tiến trình đang chạy cũng như tắt ứng dụng bị treo (Not Responding), ta dùng công cụ nào?",
     ["Task Manager", "Device Manager", "Disk Cleanup", "Disk Defragmenter"], 0,
     "Task Manager (Ctrl+Shift+Esc) hiển thị các tiến trình và mức sử dụng tài nguyên."),
    ("Tổ hợp phím nào mở trực tiếp trình quản lý tác vụ Task Manager trong Windows?",
     ["Ctrl + Shift + Esc", "Ctrl + Alt + Enter", "Alt + Shift + Esc", "Windows + Esc"], 0,
     "Ctrl + Shift + Esc mở trực tiếp Task Manager mà không qua màn hình trung gian."),
    ("Trong đường dẫn 'C:\\Tailieu\\Baitap\\Bai1.docx', phần nào là tên của ổ đĩa gốc?",
     ["C:", "Tailieu", "Baitap", "Bai1.docx"], 0,
     "C: là ký tự phân vùng ổ đĩa gốc."),
    ("Ký tự nào sau đây KHÔNG được phép xuất hiện trong tên của tệp tin hoặc thư mục trên Windows?",
     [": (Dấu hai chấm)", "_ (Dấu gạch dưới)", "- (Dấu gạch ngang)", "@ (Ký tự a còng)"], 0,
     "Windows cấm các ký tự đặc biệt: \\ / : * ? \" < > | trong tên tệp và thư mục."),
    ("Để chụp toàn bộ màn hình máy tính vào bộ nhớ tạm (Clipboard), ta dùng phím nào trên bàn phím?",
     ["Print Screen (PrtScn)", "Scroll Lock", "Pause Break", "Insert"], 0,
     "Phím Print Screen chụp lại ảnh toàn màn hình."),
    ("Công cụ có sẵn trên Windows 10/11 dùng để chụp ảnh một vùng màn hình tùy ý là gì?",
     ["Snipping Tool / Snip & Sketch (Windows + Shift + S)", "Paint 3D", "Notepad", "WordPad"], 0,
     "Snipping Tool hoặc phím tắt Win + Shift + S chụp vùng màn hình linh hoạt."),
    ("Tệp tin có phần đuôi .ZIP hoặc .RAR thuộc loại tệp tin nào sau đây?",
     ["Tệp tin nén chứa một hoặc nhiều tệp khác", "Tệp tin video độ phân giải cao", "Tệp tin âm nhạc", "Tệp tin cài đặt driver máy in"], 0,
     ".ZIP và .RAR là định dạng lưu trữ nén tệp tin phổ biến."),
    ("Để chọn nhiều tệp tin nằm LIÊN TIẾP nhau trong danh sách File Explorer, ta giữ phím nào khi nhấp chuột?",
     ["Shift", "Ctrl", "Alt", "Tab"], 0,
     "Giữ Shift để chọn một dải liên tục từ phần tử đầu đến phần tử cuối."),
    ("Để chọn nhiều tệp tin KHÔNG LIÊN TIẾP (rời rạc) nhau, ta giữ phím nào trong khi nhấp chọn từng tệp?",
     ["Ctrl", "Shift", "Alt", "Spacebar"], 0,
     "Giữ Ctrl cho phép nhấp chọn từng tệp tin rời rạc tùy ý."),
    ("Thanh nằm ở cạnh dưới cùng của màn hình Windows chứa nút Start và các biểu tượng ứng dụng gọi là gì?",
     ["Thanh tác vụ (Taskbar)", "Thanh tiêu đề (Title Bar)", "Thanh trạng thái (Status Bar)", "Thanh cuộn (Scroll Bar)"], 0,
     "Taskbar là thanh công cụ dưới đáy màn hình của Windows."),
    ("Khu vực hiển thị đồng hồ, biểu tượng mạng, âm lượng ở góc phải thanh Taskbar được gọi là gì?",
     ["Khay hệ thống (System Tray / Notification Area)", "Menu Start", "Thanh Ribbon", "Desktop Widget"], 0,
     "System Tray chứa các biểu tượng thông báo và ứng dụng chạy nền."),
    ("Trong hộp thoại Run của Windows, gõ lệnh nào để mở công cụ vẽ Paint có sẵn?",
     ["mspaint", "paintapp", "draw", "winpaint"], 0,
     "mspaint là tên tệp thực thi của ứng dụng Paint trong Windows."),
    ("Lệnh nào trong hộp thoại Run dùng để mở trình soạn thảo văn bản đơn giản Notepad?",
     ["notepad", "wordpad", "textedit", "notewin"], 0,
     "Lệnh 'notepad' mở trình soạn thảo Notepad."),
    ("Để tạo một thư mục (Folder) mới trong cửa sổ File Explorer bằng phím tắt, ta nhấn:",
     ["Ctrl + Shift + N", "Ctrl + Alt + N", "Alt + Shift + N", "Ctrl + N"], 0,
     "Ctrl + Shift + N là phím tắt tạo thư mục mới nhanh trên Windows."),
    ("Tính năng 'Disk Cleanup' trong Windows dùng để làm gì?",
     ["Dọn dẹp các tệp rác, tệp tạm thời để giải phóng dung lượng ổ đĩa", "Format xóa sạch dữ liệu trên ổ cứng", "Chống phân mảnh đĩa cứng", "Sửa chữa các sector bị hỏng trên đĩa"], 0,
     "Disk Cleanup quét và loại bỏ các file rác, file log, cache không cần thiết."),
    ("Khi muốn phục hồi lại một tệp tin đã bị xóa vào Recycle Bin về vị trí ban đầu, ta bấm chuột phải vào tệp đó và chọn:",
     ["Restore", "Cut", "Delete", "Properties"], 0,
     "Lệnh Restore khôi phục tệp về đúng đường dẫn trước khi xóa."),
    ("Để tìm kiếm một tệp tin trên máy tính Windows, ta có thể nhập tên tệp vào đâu?",
     ["Hộp tìm kiếm (Search Box) trong File Explorer hoặc trên thanh Taskbar", "Hộp thoại Run với tiền tố find:", "Bảng điều khiển Control Panel", "Cửa sổ thùng rác Recycle Bin"], 0,
     "Search Box giúp định vị file và ứng dụng nhanh chóng."),
    ("Biểu tượng 'Shortcut' trên màn hình Desktop có đặc điểm nhận dạng nào?",
     ["Có mũi tên nhỏ cong ở góc dưới bên trái biểu tượng", "Có viền màu vàng xung quanh", "Kích thước gấp đôi biểu tượng thông thường", "Có dấu gạch chéo đỏ"], 0,
     "Shortcut là lối tắt liên kết đến file gốc và có mũi tên nhỏ ở góc."),
    ("Nếu xóa một biểu tượng Shortcut trên màn hình Desktop thì tệp gốc có bị xóa không?",
     ["Không, tệp tin gốc vẫn tồn tại nguyên vẹn ở vị trí lưu trữ ban đầu", "Có, tệp tin gốc sẽ bị xóa theo ngay lập tức", "Chỉ bị xóa nếu tệp gốc nằm trong ổ C", "Tệp gốc bị di chuyển vào Recycle Bin"], 0,
     "Xóa shortcut chỉ xóa lối tắt, không ảnh hưởng đến tập tin gốc."),
    ("Thuộc tính 'Read-only' (Chỉ đọc) của một tập tin có ý nghĩa gì?",
     ["Cho phép xem nội dung nhưng không cho phép chỉnh sửa hay lưu đè lên tệp đó", "Không cho phép bất kỳ ai mở tệp ra xem", "Tệp tin tự động biến mất khi đóng lại", "Tệp tin được mã hóa bảo mật cấp cao"], 0,
     "Thuộc tính Read-only ngăn cản việc ghi đè hay sửa đổi nội dung tệp."),
    ("Thuộc tính 'Hidden' của một tập tin/thư mục trong Windows có tác dụng gì?",
     ["Ẩn tập tin/thư mục đó khỏi chế độ xem thông thường của File Explorer", "Tự động khóa mật khẩu tập tin", "Nén dung lượng tập tin xuống 50%", "Chuyển tập tin lên mạng Internet"], 0,
     "Hidden ẩn tệp tin khỏi mắt người dùng khi không bật hiển thị file ẩn."),
    ("Để xem các tệp tin và thư mục ẩn trong File Explorer trên Windows, ta cần chọn mục nào trong thẻ View?",
     ["Đánh dấu vào ô 'Hidden items'", "Chọn 'File name extensions'", "Chọn 'Compact view'", "Bấm 'Preview pane'"], 0,
     "Check mục 'Hidden items' trong tab View để hiển thị các tệp bị ẩn."),
    ("Phần mở rộng (Extension) của tệp tin thường dùng để xác định điều gì?",
     ["Định dạng tệp và phần mềm mặc định dùng để mở tệp đó", "Dung lượng chính xác của tệp tin", "Thời gian tệp tin được tạo ra", "Quyền tác giả của tệp tin"], 0,
     "Phần đuôi mở rộng (như .docx, .xlsx, .pdf) định nghĩa kiểu dữ liệu của tệp."),
    ("Bộ gõ tiếng Việt Unikey để gõ được tiếng Việt theo kiểu chữ 'aa -> â', 'aw -> ă' thì cần chọn kiểu gõ nào?",
     ["Kiểu gõ TELEX", "Kiểu gõ VNI", "Kiểu gõ VIQR", "Kiểu gõ Microsoft"], 0,
     "Telex là kiểu gõ lặp phím chữ để tạo dấu mũ và móc."),
    ("Để gõ được tiếng Việt trên font chữ 'Times New Roman' hoặc 'Arial', bảng mã trong Unikey cần chọn là gì?",
     ["Unicode", "TCVN3 (ABC)", "VNI Windows", "Vietware X"], 0,
     "Times New Roman là font chữ quốc tế chuẩn bảng mã Unicode."),
    ("Nếu sử dụng font chữ bắt đầu bằng chữ '.Vn' (ví dụ: .VnTime), bạn phải chọn bảng mã nào trong Unikey?",
     ["TCVN3 (ABC)", "Unicode", "VNI Windows", "Unicode tổ hợp"], 0,
     "Font chữ có tiền tố '.Vn' sử dụng bảng mã TCVN3 (tiêu chuẩn Việt Nam 3)."),
    ("Nếu sử dụng font chữ bắt đầu bằng chữ 'VNI-' (ví dụ: VNI-Times), bảng mã cần chọn trong Unikey là gì?",
     ["VNI Windows", "Unicode", "TCVN3 (ABC)", "BK HCM 1"], 0,
     "Font chữ bắt đầu bằng 'VNI-' yêu cầu bảng mã VNI Windows."),
    ("Để chuyển đổi nhanh giữa chế độ gõ tiếng Anh và tiếng Việt trong Unikey, ta thường dùng phím tắt nào?",
     ["Ctrl + Shift hoặc Alt + Z", "Ctrl + Alt + Del", "Shift + Space", "Windows + Space"], 0,
     "Ctrl + Shift hoặc Alt + Z là hai phím tắt mặc định chuyển ngôn ngữ trong Unikey."),
    ("Ứng dụng nào sau đây trong Windows cho phép gõ dòng lệnh dạng ký tự để điều khiển hệ thống?",
     ["Command Prompt (cmd.exe) / Windows Terminal", "Notepad", "WordPad", "File Explorer"], 0,
     "Command Prompt là giao diện dòng lệnh (CLI) của Windows."),
    ("Để xem dung lượng trống còn lại của một phân vùng ổ đĩa trong Windows, bạn thực hiện thao tác nào?",
     ["Nhấp chuột phải vào ổ đĩa trong This PC và chọn Properties", "Nhấp đúp chuột trái vào ổ đĩa", "Kéo thả ổ đĩa vào thùng rác", "Nhấn tổ hợp phím Ctrl + P"], 0,
     "Cửa sổ Properties hiển thị biểu đồ tròn dung lượng đã dùng (Used) và còn trống (Free space)."),
    ("Chức năng 'Sleep' (Ngủ) trên máy tính xách tay hoặc máy để bàn có tác dụng gì?",
     ["Đưa máy vào trạng thái tiêu thụ điện năng thấp, lưu phiên làm việc vào RAM để đánh thức nhanh", "Tắt hoàn toàn nguồn điện và xóa sạch dữ liệu trên RAM", "Khởi động lại hệ điều hành Windows", "Gỡ cài đặt các phần mềm đang chạy ngầm"], 0,
     "Sleep tạm dừng máy nhưng giữ nguyên phiên làm việc trong RAM để tiếp tục ngay khi mở máy."),
    ("Chức năng 'Hibernate' (Ngủ đông) khác với 'Sleep' ở điểm cơ bản nào?",
     ["Lưu toàn bộ phiên làm việc từ RAM vào ổ cứng rồi tắt hoàn toàn nguồn điện", "Không tiết kiệm điện bằng Sleep", "Chỉ dùng được khi có kết nối Internet", "Làm mất toàn bộ dữ liệu đang mở"], 0,
     "Hibernate ghi dữ liệu RAM vào file hiberfil.sys trên ổ cứng rồi tắt nguồn hoàn toàn."),
    ("Để định dạng lại (Format) một chiếc USB để xóa sạch dữ liệu và tạo cấu trúc lưu trữ mới, ta nhấp chuột phải vào USB và chọn:",
     ["Format...", "Eject", "Rename", "Properties"], 0,
     "Lệnh Format dùng để định dạng và xóa toàn bộ dữ liệu trên thiết bị lưu trữ."),
    ("Khi muốn rút một chiếc USB ra khỏi máy tính một cách an toàn tránh lỗi dữ liệu, ta nên thực hiện thao tác nào trước?",
     ["Nhấp chuột phải vào USB hoặc biểu tượng ở khay hệ thống và chọn 'Eject'", "Rút thẳng USB ra khỏi cổng khi đèn đang nhấp nháy", "Tắt màn hình máy tính trước khi rút", "Đổi tên USB thành Eject"], 0,
     "Lệnh Eject đảm bảo hệ điều hành đã ghi xong toàn bộ dữ liệu tạm thời ra USB trước khi ngắt kết nối.")
]

for q_text, opts, ans, exp in m2_data:
    questions.append({
        "id": len(questions) + 1,
        "module": 2,
        "moduleName": modules_info[2],
        "question": q_text,
        "options": opts,
        "answer": ans,
        "explanation": exp
    })

# Module 3: Xử lý văn bản cơ bản - MS Word (IU03) - 50 questions
m3_data = [
    ("Định dạng phần mở rộng mặc định của tài liệu Microsoft Word từ phiên bản 2007 trở về sau là gì?",
     [".docx", ".doc", ".txt", ".pdf"], 0,
     ".docx là định dạng tài liệu XML nén chuẩn của MS Word từ phiên bản 2007."),
    ("Trong MS Word, tổ hợp phím nào sau đây dùng để lưu văn bản hiện hành?",
     ["Ctrl + S", "Ctrl + O", "Ctrl + N", "Ctrl + P"], 0,
     "Ctrl + S (Save) lưu tài liệu đang soạn thảo."),
    ("Để tạo một tài liệu văn bản mới trắng tinh trong MS Word, ta dùng phím tắt nào?",
     ["Ctrl + N", "Ctrl + O", "Ctrl + W", "Ctrl + M"], 0,
     "Ctrl + N (New) tạo một file tài liệu trống mới."),
    ("Để mở một tệp tài liệu đã có sẵn trên máy tính trong MS Word, phím tắt là:",
     ["Ctrl + O", "Ctrl + N", "Ctrl + S", "Ctrl + E"], 0,
     "Ctrl + O (Open) mở hộp thoại chọn tệp để mở."),
    ("Để in ấn tài liệu hiện hành ra máy in trong MS Word, ta nhấn tổ hợp phím:",
     ["Ctrl + P", "Ctrl + I", "Ctrl + J", "Ctrl + K"], 0,
     "Ctrl + P (Print) mở cửa sổ thiết lập in ấn."),
    ("Để căn giữa (Center) đoạn văn bản đang chọn, ta nhấn tổ hợp phím nào?",
     ["Ctrl + E", "Ctrl + L", "Ctrl + R", "Ctrl + J"], 0,
     "Ctrl + E dùng để căn giữa đoạn văn."),
    ("Để căn lề trái (Align Left) cho đoạn văn bản, ta dùng tổ hợp phím nào?",
     ["Ctrl + L", "Ctrl + R", "Ctrl + E", "Ctrl + J"], 0,
     "Ctrl + L (Left) căn chỉnh văn bản sát lề bên trái."),
    ("Để căn lề phải (Align Right) cho đoạn văn bản, ta dùng tổ hợp phím nào?",
     ["Ctrl + R", "Ctrl + L", "Ctrl + E", "Ctrl + J"], 0,
     "Ctrl + R (Right) căn chỉnh văn bản sát lề bên phải."),
    ("Để căn đều cả hai bên lề (Justify) cho đoạn văn bản, ta dùng tổ hợp phím nào?",
     ["Ctrl + J", "Ctrl + E", "Ctrl + B", "Ctrl + H"], 0,
     "Ctrl + J (Justify) dàn đều văn bản thẳng hai bên lề trái và phải."),
    ("Để định dạng chữ IN ĐẬM (Bold) cho khối văn bản được chọn, ta dùng tổ hợp phím:",
     ["Ctrl + B", "Ctrl + I", "Ctrl + U", "Ctrl + D"], 0,
     "Ctrl + B (Bold) bật/tắt định dạng in đậm chữ."),
    ("Để định dạng chữ IN NGHIÊNG (Italic) cho khối văn bản được chọn, ta dùng tổ hợp phím:",
     ["Ctrl + I", "Ctrl + B", "Ctrl + U", "Ctrl + K"], 0,
     "Ctrl + I (Italic) bật/tắt định dạng in nghiêng chữ."),
    ("Để định dạng chữ GẠCH CHÂN (Underline) cho khối văn bản được chọn, ta dùng tổ hợp phím:",
     ["Ctrl + U", "Ctrl + B", "Ctrl + I", "Ctrl + D"], 0,
     "Ctrl + U (Underline) bật/tắt đường kẻ gạch chân dưới văn bản."),
    ("Để mở hộp thoại Tìm kiếm (Find) trong văn bản Word, ta dùng phím tắt nào?",
     ["Ctrl + F", "Ctrl + H", "Ctrl + G", "Ctrl + K"], 0,
     "Ctrl + F (Find) mở khung tìm kiếm từ/cụm từ trong tài liệu."),
    ("Để mở hộp thoại Tìm kiếm và Thay thế (Find and Replace) trong MS Word, ta dùng phím tắt:",
     ["Ctrl + H", "Ctrl + F", "Ctrl + R", "Ctrl + T"], 0,
     "Ctrl + H mở trực tiếp tab Replace trong hộp thoại Find & Replace."),
    ("Để ngắt trang văn bản cưỡng bức (Page Break) sang một trang mới ngay tại vị trí con trỏ, ta nhấn:",
     ["Ctrl + Enter", "Shift + Enter", "Alt + Enter", "Enter"], 0,
     "Ctrl + Enter chèn dấu ngắt trang đẩy nội dung sau con trỏ sang đầu trang mới."),
    ("Thao tác nhấn phím 'Shift + Enter' trong văn bản MS Word có tác dụng gì?",
     ["Xuống dòng nhưng không tách thành đoạn mới (Soft break)", "Ngắt sang một trang mới", "Lưu văn bản ngay lập tức", "Chèn thêm một dòng trống"], 0,
     "Shift + Enter ngắt dòng trong cùng một đoạn văn bản (line break)."),
    ("Để tăng hoặc giảm cỡ chữ nhanh cho văn bản đang chọn, ta có thể dùng tổ hợp phím nào?",
     ["Ctrl + ] (Tăng) và Ctrl + [ (Giảm)", "Ctrl + Shift + > và Ctrl + Shift + <", "Cả 2 cách trên đều đúng", "Chỉ dùng chuột chọn trên thanh công cụ"], 2,
     "Cả phím tắt Ctrl + [/] và Ctrl + Shift + </> đều điều chỉnh cỡ chữ nhanh."),
    ("Để tạo chữ chỉ số dưới (Subscript, ví dụ: H2O), ta sử dụng tổ hợp phím nào?",
     ["Ctrl + = (Dấu bằng)", "Ctrl + Shift + = (Dấu cộng)", "Alt + =", "Ctrl + Alt + ="], 0,
     "Ctrl + = tạo chữ chỉ số dưới (Subscript)."),
    ("Để tạo chữ chỉ số trên (Superscript, ví dụ: X2, m2), ta sử dụng tổ hợp phím nào?",
     ["Ctrl + Shift + = (hoặc Ctrl + Shift + +)", "Ctrl + =", "Alt + Shift + =", "Ctrl + Alt + +"], 0,
     "Ctrl + Shift + = tạo chữ chỉ số trên (Superscript)."),
    ("Chức năng 'Format Painter' (hình cây chổi sơn) trên thẻ Home có công dụng gì?",
     ["Sao chép định dạng của vùng văn bản này áp dụng cho vùng văn bản khác", "Vẽ hình chữ nhật hoặc hình tròn", "Tô màu nền cho toàn bộ trang văn bản", "Dọn dẹp virus trong tài liệu"], 0,
     "Format Painter sao chép kiểu phông, cỡ chữ, màu sắc... của đoạn mẫu sang đoạn đích."),
    ("Để chèn một bảng biểu (Table) vào văn bản Word, ta vào thẻ nào trên thanh Ribbon?",
     ["Insert -> Table", "Home -> Table", "Layout -> Table", "Design -> Table"], 0,
     "Thẻ Insert chứa các lệnh chèn bảng biểu, hình ảnh, hình vẽ vào tài liệu."),
    ("Khi đang ở trong một ô của bảng (Table), phím nào dùng để di chuyển con trỏ sang ô tiếp theo bên phải?",
     ["Tab", "Enter", "Spacebar", "Shift"], 0,
     "Phím Tab chuyển con trỏ sang ô kế tiếp; nếu ở ô cuối cùng sẽ tạo thêm dòng mới."),
    ("Để gộp nhiều ô đang chọn trong bảng thành một ô duy nhất, ta dùng lệnh nào?",
     ["Merge Cells", "Split Cells", "Delete Cells", "Insert Cells"], 0,
     "Merge Cells hợp nhất các ô được chọn thành 1 ô lớn."),
    ("Để chia một ô trong bảng thành nhiều ô nhỏ hơn, ta sử dụng lệnh nào?",
     ["Split Cells", "Merge Cells", "Split Table", "Cell Spacing"], 0,
     "Split Cells chia tách ô hiện tại thành số hàng và cột tùy chọn."),
    ("Để chia văn bản thành nhiều cột dạng bài báo (Columns), ta vào thẻ nào trên thanh Ribbon?",
     ["Layout -> Columns", "Home -> Columns", "Insert -> Columns", "View -> Columns"], 0,
     "Thẻ Layout quản lý bố cục trang gồm Margins, Orientation, Size, Columns..."),
    ("Để tạo chữ cái lớn đầu dòng đoạn văn (Drop Cap), ta vào thẻ nào?",
     ["Insert -> Drop Cap", "Home -> Drop Cap", "Layout -> Drop Cap", "Design -> Drop Cap"], 0,
     "Lệnh Drop Cap nằm trong nhóm Text của thẻ Insert."),
    ("Chức năng đặt khoảng cách lề trang giấy (Margins) trong Word nằm ở thẻ nào?",
     ["Layout -> Margins", "Home -> Margins", "Insert -> Margins", "Review -> Margins"], 0,
     "Layout -> Margins cho phép chỉnh kích thước lề trên, dưới, trái, phải."),
    ("Để thay đổi hướng in của trang giấy từ dạng dọc (Portrait) sang dạng ngang (Landscape), ta chọn mục nào?",
     ["Layout -> Orientation", "Layout -> Size", "Layout -> Margins", "Design -> Page Color"], 0,
     "Orientation chứa 2 tùy chọn hướng giấy: Portrait (dọc) và Landscape (ngang)."),
    ("Muốn chèn tiêu đề đầu trang (Header) và tiêu đề chân trang (Footer), ta vào thẻ nào?",
     ["Insert -> Header & Footer", "Home -> Header & Footer", "Layout -> Header & Footer", "References -> Header & Footer"], 0,
     "Header và Footer nằm trong thẻ Insert."),
    ("Để chèn số trang tự động vào tài liệu trong MS Word, ta sử dụng lệnh nào?",
     ["Insert -> Page Number", "Home -> Numbering", "Layout -> Page Setup", "Review -> Word Count"], 0,
     "Insert -> Page Number chèn số trang ở đầu, cuối hoặc lề trang."),
    ("Để chèn chữ mờ chìm dưới trang văn bản nhằm chống sao chép (ví dụ: CONFIDENTIAL, BẢN NHÁP), ta dùng tính năng nào?",
     ["Watermark (trong thẻ Design)", "Page Borders", "WordArt", "Text Box"], 0,
     "Watermark tạo chữ hoặc hình ảnh chìm làm hình nền bản quyền cho trang."),
    ("Để chèn một hình ảnh từ máy tính vào văn bản, ta chọn lệnh nào?",
     ["Insert -> Pictures", "Home -> Pictures", "Layout -> Pictures", "Design -> Pictures"], 0,
     "Insert -> Pictures mở hộp thoại chọn tệp ảnh để chèn vào văn bản."),
    ("Tính năng 'Wrap Text' khi chèn ảnh vào Word có tác dụng gì?",
     ["Quy định cách hiển thị và bố trí văn bản xung quanh bức ảnh", "Thay đổi màu sắc độ nét của bức ảnh", "Cắt tỉa kích thước bức ảnh", "Làm mờ bức ảnh thành hình nền"], 0,
     "Wrap Text (Square, Tight, Behind Text, In Front of Text...) xác định tương tác giữa ảnh và chữ."),
    ("Để vẽ các hình khối học cơ bản như hình tròn, mũi tên, ngôi sao... ta vào mục nào?",
     ["Insert -> Shapes", "Insert -> SmartArt", "Insert -> Chart", "Home -> Drawing"], 0,
     "Insert -> Shapes chứa thư viện hình vẽ vector cơ bản."),
    ("Chức năng 'SmartArt' trong MS Word dùng để làm gì?",
     ["Tạo các sơ đồ tổ chức, quy trình, biểu đồ phân cấp đẹp mắt", "Chèn ảnh nghệ thuật từ Internet", "Vẽ biểu đồ số liệu cột và tròn", "Tự động sửa lỗi ngữ pháp văn bản"], 0,
     "SmartArt tạo các sơ đồ thông minh thể hiện cấu trúc quy trình, phân cấp."),
    ("Để chèn công thức toán học chuyên nghiệp vào Word, ta sử dụng tính năng nào?",
     ["Insert -> Equation", "Insert -> Symbol", "Insert -> Object", "Home -> Font"], 0,
     "Insert -> Equation cung cấp bộ công cụ gõ ký hiệu và công thức toán học chuẩn."),
    ("Để kiểm tra tổng số từ, số ký tự, số trang của tài liệu Word, ta xem ở đâu?",
     ["Thanh trạng thái (Status bar) ở góc dưới bên trái hoặc thẻ Review -> Word Count", "Thẻ File -> Save As", "Thẻ Design -> Themes", "Thẻ Layout -> Columns"], 0,
     "Thanh Status bar hiển thị ngay lập tức số trang và số từ (Words)."),
    ("Để tạo danh sách liệt kê dạng dấu chấm đầu dòng (Bullets), ta vào nhóm Paragraph trên thẻ Home và chọn:",
     ["Biểu tượng Bullets", "Biểu tượng Numbering", "Biểu tượng Multilevel List", "Biểu tượng Sort"], 0,
     "Bullets tạo danh sách các mục không sắp thứ tự bằng các ký hiệu hình tròn, vuông..."),
    ("Để tạo danh sách liệt kê đánh số thứ tự tự động (1, 2, 3... hoặc a, b, c...), ta chọn biểu tượng nào?",
     ["Numbering", "Bullets", "Line Spacing", "Shading"], 0,
     "Numbering tạo danh sách có thứ tự chữ số hoặc bảng chữ cái."),
    ("Khoảng cách giãn dòng chuẩn (Line Spacing) thường được quy định trong văn bản hành chính là:",
     ["1.5 lines (hoặc 1.3 - 1.5)", "3.0 lines", "0.5 line", "Double 2.0 lines"], 0,
     "Quy định văn bản hành chính thường dùng giãn dòng 1.3 - 1.5 lines."),
    ("Để đặt các điểm dừng Tab (Tab stop) trên thước kẻ, ta có thể thao tác bằng cách:",
     ["Nhấp chuột trực tiếp lên vị trí mong muốn trên thanh Thước kẻ (Ruler)", "Nhấn phím Enter liên tục", "Nhấn phím Spacebar nhiều lần", "Dùng công cụ vẽ nét thẳng"], 0,
     "Nhấp chuột lên thanh Ruler tạo nhanh điểm dừng Tab trái, phải hoặc giữa."),
    ("Chức năng trộn thư (Mail Merge) trong Word nằm ở thẻ nào trên thanh Ribbon?",
     ["Mailings", "Review", "References", "View"], 0,
     "Thẻ Mailings dành riêng cho việc tạo thư mời, nhãn thư hàng loạt từ danh sách dữ liệu."),
    ("Để tạo mục lục tự động (Table of Contents) nhanh chóng, các tiêu đề trong văn bản cần được định dạng bằng:",
     ["Các kiểu dáng Heading (Heading 1, Heading 2...) trong thẻ Home", "Bôi đậm chữ và gõ dấu cách", "Đổi màu chữ thành màu đỏ", "Dùng phím Tab căn lề thụt vào"], 0,
     "Word dựa vào cấu trúc Heading 1, 2, 3 để tự động trích xuất bảng mục lục."),
    ("Thẻ nào trên thanh Ribbon dùng để chèn chú thích cuối trang (Footnote)?",
     ["References -> Insert Footnote", "Review -> New Comment", "Insert -> Footer", "Layout -> Breaks"], 0,
     "References chứa công cụ trích dẫn khoa học và chú thích Footnote / Endnote."),
    ("Chức năng 'Track Changes' trong thẻ Review có công dụng gì?",
     ["Theo dõi và ghi nhận mọi thay đổi chỉnh sửa trên tài liệu để người kiểm duyệt xem xét", "Đếm số lần người dùng in tài liệu", "Tự động sao lưu tài liệu mỗi 5 phút", "Kiểm tra tốc độ gõ phím của tác giả"], 0,
     "Track Changes đánh dấu các vị trí thêm, xóa, sửa trong quá trình cộng tác văn bản."),
    ("Để phóng to hoặc thu nhỏ góc nhìn tài liệu mà không làm thay đổi cỡ chữ in ấn, ta dùng:",
     ["Thanh trượt thu phóng (Zoom slider) ở góc dưới cùng bên phải", "Thay đổi giá trị Font Size", "Nhấn tổ hợp phím Ctrl + P", "Vào Layout -> Page Setup"], 0,
     "Thanh Zoom chỉ thay đổi tỷ lệ hiển thị trên màn hình máy tính."),
    ("Để hiển thị hoặc ẩn thanh Thước kẻ (Ruler) trong cửa sổ Word, ta vào thẻ nào?",
     ["View -> đánh dấu vào ô Ruler", "Home -> Ruler", "Insert -> Ruler", "Layout -> Ruler"], 0,
     "Thẻ View quản lý hiển thị Ruler, Gridlines, Navigation Pane."),
    ("Phím F12 trong Microsoft Word dùng để thực hiện lệnh nào?",
     ["Mở hộp thoại Save As (Lưu với tên mới hoặc định dạng mới)", "Lưu đè tài liệu (Save)", "Mở tệp mới (Open)", "Đóng ứng dụng Word"], 0,
     "F12 là phím tắt của lệnh Save As."),
    ("Để xuất tài liệu Word sang định dạng tệp tin PDF không cho chỉnh sửa trực tiếp, ta vào:",
     ["File -> Export (hoặc Save As chọn định dạng PDF)", "Home -> Convert to PDF", "Design -> Make PDF", "Layout -> Page Setup"], 0,
     "Lệnh File -> Export -> Create PDF/XPS tạo file PDF chuẩn."),
    ("Tổ hợp phím 'Ctrl + W' hoặc 'Ctrl + F4' trong MS Word dùng để làm gì?",
     ["Đóng tài liệu hiện hành mà không thoát hoàn toàn khỏi ứng dụng Word", "Tạo một tài liệu mới", "Mở tài liệu gần đây", "Lưu tất cả tài liệu đang mở"], 0,
     "Ctrl + W đóng cửa sổ tệp đang làm việc.")
]

for q_text, opts, ans, exp in m3_data:
    questions.append({
        "id": len(questions) + 1,
        "module": 3,
        "moduleName": modules_info[3],
        "question": q_text,
        "options": opts,
        "answer": ans,
        "explanation": exp
    })

# Module 4: Sử dụng bảng tính cơ bản - MS Excel (IU04) - 50 questions
m4_data = [
    ("Định dạng phần mở rộng mặc định của tệp bảng tính Microsoft Excel từ phiên bản 2007 là gì?",
     [".xlsx", ".xls", ".csv", ".xlsm"], 0,
     ".xlsx là định dạng workbook chuẩn của Excel từ bản 2007."),
    ("Trong MS Excel, giao điểm giữa một cột và một hàng được gọi là gì?",
     ["Ô tính (Cell)", "Bảng tính (Sheet)", "Khối ô (Range)", "Trường (Field)"], 0,
     "Cell (ô) là đơn vị cơ bản lưu trữ dữ liệu tại giao điểm của cột và hàng."),
    ("Tên địa chỉ của một ô tính trong Excel được cấu tạo theo quy tắc nào?",
     ["Tên cột trước, chỉ số hàng sau (Ví dụ: B5, C10)", "Chỉ số hàng trước, tên cột sau (Ví dụ: 5B, 10C)", "Chỉ gồm chữ cái", "Chỉ gồm các chữ số"], 0,
     "Quy tắc chuẩn đặt địa chỉ ô là chữ cái đại diện cột đi kèm số hàng, ví dụ A1, D8."),
    ("Để bắt đầu nhập một công thức hoặc hàm tính toán trong Excel, ký tự đầu tiên bắt buộc phải là:",
     ["Dấu bằng (=)", "Dấu cộng (+)", "Dấu hai chấm (:)", "Dấu hỏi (?)"], 0,
     "Dấu = báo hiệu cho Excel biết đây là biểu thức tính toán chứ không phải chuỗi ký tự."),
    ("Hàm nào sau đây dùng để tính TỔNG các giá trị số trong một phạm vi ô?",
     ["SUM", "AVERAGE", "COUNT", "MAX"], 0,
     "Hàm SUM tính tổng tất cả các số trong danh sách tham số."),
    ("Hàm nào dùng để tính GIÁ TRỊ TRUNG BÌNH của một tập hợp các số?",
     ["AVERAGE", "MEAN", "SUM", "MEDIAN"], 0,
     "Hàm AVERAGE tính trung bình cộng của các đối số."),
    ("Hàm nào sau đây dùng để tìm GIÁ TRỊ LỚN NHẤT trong một phạm vi dữ liệu?",
     ["MAX", "MIN", "LARGE", "TOP"], 0,
     "Hàm MAX trả về số lớn nhất trong tập giá trị."),
    ("Hàm nào sau đây dùng để tìm GIÁ TRỊ NHỎ NHẤT trong một phạm vi dữ liệu?",
     ["MIN", "MAX", "SMALL", "BOTTOM"], 0,
     "Hàm MIN trả về giá trị nhỏ nhất."),
    ("Hàm COUNT trong Excel có chức năng chính là gì?",
     ["Đếm số lượng ô chứa dữ liệu kiểu số", "Đếm tất cả các ô không rỗng bất kể kiểu dữ liệu", "Đếm các ô có điều kiện", "Đếm số ô rỗng trong bảng"], 0,
     "COUNT chỉ đếm các ô chứa giá trị số (numbers)."),
    ("Để đếm tất cả các ô KHÔNG TRỐNG (chứa số, chữ hoặc ký tự bất kỳ), ta dùng hàm nào?",
     ["COUNTA", "COUNT", "COUNTBLANK", "COUNTIF"], 0,
     "COUNTA (Count All) đếm mọi ô không rỗng."),
    ("Hàm nào dùng để đếm số lượng ô THỎA MÃN MỘT ĐIỀU KIỆN cho trước?",
     ["COUNTIF", "SUMIF", "COUNT", "IF"], 0,
     "Cú pháp =COUNTIF(range, criteria) đếm các ô thỏa mãn điều kiện criteria."),
    ("Hàm nào dùng để TÍNH TỔNG các ô thỏa mãn một điều kiện nhất định?",
     ["SUMIF", "COUNTIF", "TOTALIF", "SUM"], 0,
     "Cú pháp =SUMIF(range, criteria, [sum_range]) tính tổng có điều kiện."),
    ("Hàm logic nào kiểm tra một điều kiện và trả về giá trị thứ nhất nếu đúng, giá trị thứ hai nếu sai?",
     ["IF", "AND", "OR", "NOT"], 0,
     "Cú pháp: =IF(logical_test, value_if_true, value_if_false)."),
    ("Công thức =IF(7 >= 5, \"Đạt\", \"Hỏng\") sẽ trả về kết quả là gì?",
     ["Đạt", "Hỏng", "TRUE", "7"], 0,
     "Vì biểu thức 7 >= 5 đúng (TRUE), hàm trả về giá trị 'Đạt'."),
    ("Trong Excel, địa chỉ $A$1 thuộc loại địa chỉ nào?",
     ["Địa chỉ tuyệt đối", "Địa chỉ tương đối", "Địa chỉ hỗn hợp", "Địa chỉ tương đối theo dòng"], 0,
     "Có cả 2 dấu $ trước tên cột và số hàng nên là địa chỉ tuyệt đối cố định."),
    ("Địa chỉ A1 (không có dấu $) thuộc loại địa chỉ nào?",
     ["Địa chỉ tương đối", "Địa chỉ tuyệt đối", "Địa chỉ hỗn hợp", "Địa chỉ tham chiếu ngoài"], 0,
     "Địa chỉ tương đối sẽ tự động thay đổi tương ứng khi sao chép công thức sang ô khác."),
    ("Địa chỉ $A1 hoặc A$1 được gọi là loại địa chỉ gì?",
     ["Địa chỉ hỗn hợp", "Địa chỉ tuyệt đối hoàn toàn", "Địa chỉ tương đối hoàn toàn", "Địa chỉ hằng số"], 0,
     "Địa chỉ hỗn hợp cố định 1 thành phần (cố định cột hoặc cố định hàng)."),
    ("Để chuyển đổi qua lại nhanh giữa các loại địa chỉ tương đối, tuyệt đối, hỗn hợp, ta dùng phím:",
     ["F4", "F2", "F9", "F12"], 0,
     "Phím F4 thay đổi nhanh giữa A1, $A$1, A$1, $A1 khi đang chọn ô trong công thức."),
    ("Khi một ô trong Excel hiển thị lỗi '#####', nguyên nhân thông thường là do:",
     ["Độ rộng của cột quá hẹp không đủ để hiển thị hết số liệu", "Nhập sai tên hàm", "Chia một số cho số 0", "Dữ liệu bị virus mã hóa"], 0,
     "Lỗi ##### thường xảy ra khi cột không đủ rộng để hiển thị chuỗi số hoặc ngày tháng."),
    ("Thông báo lỗi '#DIV/0!' trong công thức Excel có ý nghĩa gì?",
     ["Công thức thực hiện phép chia cho số 0 hoặc ô rỗng", "Tên hàm bị viết sai chính tả", "Không tìm thấy giá trị tham chiếu", "Kiểu dữ liệu bị xung đột"], 0,
     "#DIV/0! (Division by zero) xuất hiện khi chia một giá trị cho 0."),
    ("Thông báo lỗi '#NAME?' trong Excel xuất hiện khi nào?",
     ["Excel không nhận diện được tên hàm hoặc tên vùng dữ liệu (thường do gõ sai tên)", "Chia một số cho số 0", "Dữ liệu vượt quá giới hạn", "Cột quá hẹp"], 0,
     "#NAME? xảy ra khi gõ sai tên hàm (ví dụ gõ =SUMM(...) thay vì =SUM(...))."),
    ("Thông báo lỗi '#VALUE!' xảy ra khi nào?",
     ["Dữ liệu truyền vào công thức không đúng kiểu mong đợi (ví dụ lấy chuỗi chữ cộng với số)", "Lỗi chia cho 0", "Hàm không tìm thấy kết quả trong bảng dò", "Ô tính bị khóa"], 0,
     "#VALUE! báo lỗi đối số không đúng kiểu dữ liệu trong phép toán."),
    ("Hàm nào sau đây dùng để dò tìm giá trị theo CỘT từ một bảng tham chiếu?",
     ["VLOOKUP", "HLOOKUP", "INDEX", "MATCH"], 0,
     "VLOOKUP (Vertical Lookup) dò tìm giá trị theo cột dọc."),
    ("Hàm nào sau đây dùng để dò tìm giá trị theo HÀNG từ một bảng tham chiếu?",
     ["HLOOKUP", "VLOOKUP", "LOOKUP", "ROW"], 0,
     "HLOOKUP (Horizontal Lookup) dò tìm giá trị theo hàng ngang."),
    ("Trong hàm VLOOKUP(lookup_value, table_array, col_index_num, range_lookup), tham số range_lookup = 0 (hoặc FALSE) có ý nghĩa gì?",
     ["Tìm kiếm chính xác tuyệt đối", "Tìm kiếm tương đối xấp xỉ", "Không tìm kiếm", "Bỏ qua lỗi"], 0,
     "Tham số 0 (FALSE) chỉ định VLOOKUP tìm kiếm chính xác giá trị."),
    ("Kết quả của công thức =MOD(17, 5) trong Excel là bao nhiêu?",
     ["2", "3", "3.4", "1"], 0,
     "Hàm MOD trả về số dư của phép chia: 17 chia 5 bằng 3 dư 2."),
    ("Hàm INT(8.9) trong Excel sẽ trả về kết quả là gì?",
     ["8", "9", "8.9", "0.9"], 0,
     "Hàm INT làm tròn xuống số nguyên gần nhất nhỏ hơn hoặc bằng nó, nên INT(8.9) = 8."),
    ("Công thức =ROUND(123.456, 2) cho kết quả làm tròn là bao nhiêu?",
     ["123.46", "123.45", "123.5", "123"], 0,
     "Hàm ROUND làm tròn đến 2 chữ số thập phân: chữ số thứ 3 là 6 >= 5 nên làm tròn lên 123.46."),
    ("Hàm LEFT(\"BACHKHOA\", 4) trả về chuỗi ký tự nào?",
     ["BACH", "KHOA", "ACHK", "BACHK"], 0,
     "Hàm LEFT lấy 4 ký tự tính từ bên trái chuỗi."),
    ("Hàm RIGHT(\"TIN HOC\", 3) trả về chuỗi ký tự nào?",
     ["HOC", "TIN", "N HOC", " HOC"], 0,
     "Hàm RIGHT lấy 3 ký tự từ bên phải chuỗi."),
    ("Hàm MID(\"EXCEL2026\", 3, 3) trả về kết quả nào?",
     ["CEL", "EXC", "L20", "202"], 0,
     "MID lấy từ vị trí thứ 3 (ký tự C) với độ dài 3 ký tự -> 'CEL'."),
    ("Hàm LEN(\"TRAC NGHIEM\") trả về độ dài chuỗi là bao nhiêu ký tự?",
     ["11", "10", "12", "9"], 0,
     "Chuỗi 'TRAC NGHIEM' gồm 4 + 1(dấu cách) + 6 = 11 ký tự."),
    ("Hàm TODAY() trong Excel trả về giá trị gì?",
     ["Ngày tháng năm hiện tại của hệ thống máy tính", "Ngày và giờ phút giây hiện tại", "Chỉ trả về năm hiện tại", "Ngày đầu tiên của tháng"], 0,
     "TODAY() lấy ngày hiện tại (không có giờ)."),
    ("Hàm NOW() trong Excel trả về giá trị gì?",
     ["Cả ngày tháng năm và giờ phút giây hiện tại của hệ thống", "Chỉ trả về ngày hiện tại", "Chỉ trả về giờ hiện tại", "Thời gian máy tính đã bật"], 0,
     "NOW() trả về cả thông tin ngày và giờ hiện tại."),
    ("Để định dạng dữ liệu kiểu số hiển thị dấu phân cách hàng nghìn (1,000,000), ta vào thẻ Home và chọn:",
     ["Biểu tượng dấu phẩy Comma Style (,) trong nhóm Number", "Biểu tượng %", "Biểu tượng $", "Biểu tượng tăng số thập phân"], 0,
     "Comma Style định dạng số có phân tách hàng nghìn và 2 chữ số thập phân."),
    ("Để gộp các ô lại với nhau và căn giữa nội dung vào chính giữa, ta dùng lệnh:",
     ["Merge & Center", "Center Across", "Wrap Text", "AutoFit"], 0,
     "Merge & Center gộp nhiều ô và căn dữ liệu ra giữa ô mới gộp."),
    ("Tính năng 'Wrap Text' trong Excel có tác dụng gì đối với một ô tính?",
     ["Tự động ngắt dòng văn bản dài xuống nhiều dòng trong cùng một ô", "Gộp ô này với ô bên dưới", "Xóa bớt chữ thừa", "Thu nhỏ cỡ chữ lại"], 0,
     "Wrap Text cho phép hiển thị toàn bộ nội dung dài bằng cách tăng chiều cao dòng."),
    ("Để cố định dòng tiêu đề hoặc cột đầu tiên khi cuộn trang bảng tính xuống dưới, ta dùng tính năng:",
     ["Freeze Panes (trong thẻ View)", "Split Panes", "Hide Rows", "Lock Cells"], 0,
     "Freeze Panes cố định hàng/cột tiêu đề giúp dễ theo dõi bảng dữ liệu lớn."),
    ("Để lọc dữ liệu tự động trong bảng tính, ta vào thẻ Data và chọn biểu tượng hình cái phễu có tên là gì?",
     ["Filter", "Sort", "Advanced", "Consolidate"], 0,
     "Filter (AutoFilter) tạo các nút mũi tên thả xuống để lọc dữ liệu."),
    ("Để sắp xếp dữ liệu bảng tính theo thứ tự tăng dần từ A đến Z, ta dùng lệnh:",
     ["Sort A to Z (trong thẻ Data hoặc Home)", "Sort Z to A", "Filter", "Data Validation"], 0,
     "Sort A to Z sắp xếp dữ liệu tăng dần (số nhỏ đến lớn, chữ cái A đến Z)."),
    ("Để vẽ biểu đồ hình cột hoặc hình tròn từ bảng dữ liệu trong Excel, ta vào thẻ nào?",
     ["Insert -> Charts", "Home -> Charts", "Data -> Charts", "Page Layout -> Charts"], 0,
     "Thẻ Insert chứa nhóm Charts cung cấp đa dạng các dạng biểu đồ trực quan."),
    ("Biểu đồ hình tròn (Pie Chart) thường thích hợp nhất cho trường hợp nào sau đây?",
     ["Thể hiện cơ cấu tỷ trọng phần trăm của các thành phần trong tổng thể", "So sánh số lượng qua nhiều năm", "Biểu diễn xu hướng biến động nhiệt độ", "Thể hiện dữ liệu chứng khoán theo phút"], 0,
     "Pie Chart trực quan hóa tỷ lệ phần trăm đóng góp của các nhóm trong tổng thể 100%."),
    ("Tính năng 'Conditional Formatting' trên thẻ Home dùng để làm gì?",
     ["Tự động đổi màu nền hoặc màu chữ của các ô dựa trên giá trị điều kiện của chúng", "Tạo mật khẩu bảo vệ ô", "Định dạng kiểu tiền tệ cho ô", "Khóa công thức không cho chỉnh sửa"], 0,
     "Định dạng có điều kiện (Conditional Formatting) làm nổi bật các ô thỏa tiêu chí."),
    ("Để chèn thêm một cột mới vào bên trái cột đang chọn, ta nhấp chuột phải vào tên cột và chọn:",
     ["Insert", "Delete", "Add Column", "Paste"], 0,
     "Lệnh Insert trên tiêu đề cột sẽ chèn một cột mới ngay vị trí hiện tại."),
    ("Để xóa hoàn toàn một hàng trong bảng tính Excel, ta nhấp chuột phải vào số thứ tự hàng và chọn:",
     ["Delete", "Clear Contents", "Cut", "Hide"], 0,
     "Delete xóa bỏ hoàn toàn dòng đó và dồn các dòng bên dưới lên."),
    ("Lệnh 'Clear Contents' khi nhấp chuột phải vào một ô có tác dụng gì?",
     ["Chỉ xóa sạch nội dung dữ liệu bên trong ô nhưng giữ nguyên định dạng của ô", "Xóa bỏ luôn ô tính đó", "Xóa màu nền nhưng giữ chữ", "Xóa công thức và thay bằng số 0"], 0,
     "Clear Contents xóa dữ liệu (phím Delete) mà không làm mất định dạng đường viền hay màu sắc."),
    ("Phím tắt nào dùng để chỉnh sửa nội dung đang có trong một ô tính mà không xóa dữ liệu cũ?",
     ["F2", "F1", "F4", "Enter"], 0,
     "Nhấn F2 đưa con trỏ vào cuối ô để chỉnh sửa tiếp dữ liệu."),
    ("Để tính tổng nhanh một cột số liệu chỉ bằng một lần nhấp chuột, ta dùng công cụ nào trên thẻ Home?",
     ["AutoSum (ký hiệu Σ)", "AutoFormat", "Fill Series", "Calculate Now"], 0,
     "Nút AutoSum (Alt + =) tự động chèn hàm SUM cho dải ô phía trên hoặc bên trái."),
    ("Để di chuyển con trỏ xuống ô ngay bên dưới trong bảng tính, ta nhấn phím:",
     ["Enter", "Tab", "Shift + Tab", "Spacebar"], 0,
     "Enter chuyển xuống ô dưới, Tab chuyển sang ô bên phải."),
    ("Trong Excel, toán tử nào dùng để nối hai chuỗi văn bản lại với nhau?",
     ["Toán tử & (Dấu và)", "Toán tử +", "Toán tử *", "Toán tử #"], 0,
     "Toán tử & (ampersand) dùng để ghép chuỗi ký tự, ví dụ: =\"A\" & \"B\" cho ra \"AB\".")
]

for q_text, opts, ans, exp in m4_data:
    questions.append({
        "id": len(questions) + 1,
        "module": 4,
        "moduleName": modules_info[4],
        "question": q_text,
        "options": opts,
        "answer": ans,
        "explanation": exp
    })

# Module 5: Sử dụng trình chiếu cơ bản - MS PowerPoint (IU05) - 50 questions
m5_data = [
    ("Phần mở rộng mặc định của tệp trình chiếu Microsoft PowerPoint từ phiên bản 2007 trở về sau là gì?",
     [".pptx", ".ppt", ".pps", ".potx"], 0,
     ".pptx là định dạng bài thuyết trình mặc định từ PowerPoint 2007."),
    ("Để bắt đầu trình chiếu bài thuyết trình từ slide đầu tiên, ta nhấn phím nào trên bàn phím?",
     ["F5", "Shift + F5", "F7", "Ctrl + F5"], 0,
     "F5 bắt đầu trình chiếu từ slide số 1."),
    ("Để trình chiếu bài thuyết trình từ SLIDE HIỆN TẠI đang mở, ta dùng tổ hợp phím nào?",
     ["Shift + F5", "F5", "Ctrl + F5", "Alt + F5"], 0,
     "Shift + F5 chạy trình chiếu bắt đầu ngay tại slide đang làm việc."),
    ("Để kết thúc và thoát khỏi chế độ trình chiếu quay về màn hình soạn thảo, ta nhấn phím nào?",
     ["Esc (Escape)", "Enter", "Spacebar", "Backspace"], 0,
     "Phím Esc dừng chế độ chiếu slide ngay lập tức."),
    ("Để chèn thêm một Slide mới vào bài thuyết trình, ta sử dụng tổ hợp phím nào?",
     ["Ctrl + M", "Ctrl + N", "Ctrl + S", "Ctrl + D"], 0,
     "Ctrl + M chèn thêm 1 slide mới vào bài trình chiếu."),
    ("Tổ hợp phím 'Ctrl + N' trong MS PowerPoint dùng để làm gì?",
     ["Tạo một tệp bài thuyết trình mới hoàn toàn", "Chèn thêm slide mới", "Sao chép slide hiện tại", "In ấn bài thuyết trình"], 0,
     "Ctrl + N (New) mở một cửa sổ thuyết trình mới."),
    ("Để nhân bản (nhân đôi) slide đang chọn, ta có thể dùng phím tắt nào?",
     ["Ctrl + D", "Ctrl + M", "Ctrl + C", "Ctrl + K"], 0,
     "Ctrl + D (Duplicate) nhân đôi slide hoặc đối tượng đang chọn."),
    ("Khung chứa văn bản hoặc hình ảnh có sẵn trên một Slide được gọi là gì?",
     ["Placeholder", "Text frame", "Slide layout", "Template"], 0,
     "Placeholder là các hộp khung có viền nét đứt giữ chỗ cho tiêu đề, nội dung trên slide."),
    ("Thẻ nào trên thanh Ribbon dùng để chọn các mẫu thiết kế giao diện, màu sắc có sẵn cho bài thuyết trình?",
     ["Design", "Insert", "Transitions", "Slide Show"], 0,
     "Thẻ Design cung cấp các bộ chủ đề (Themes) và biến thể màu sắc."),
    ("Hiệu ứng chuyển đổi giữa các SLIDE với nhau (khi chuyển từ slide này sang slide khác) gọi là gì?",
     ["Transitions", "Animations", "SmartArt", "Slide Effects"], 0,
     "Transitions là hiệu ứng chuyển cảnh giữa các slide."),
    ("Hiệu ứng dành cho từng ĐỐI TƯỢNG (chữ, hình ảnh, biểu đồ) xuất hiện bên trong một slide gọi là gì?",
     ["Animations", "Transitions", "WordArt", "Action Settings"], 0,
     "Animations là hiệu ứng hoạt họa cho các thành phần bên trong slide."),
    ("Trong nhóm hiệu ứng Animation, nhóm hiệu ứng 'Entrance' (màu xanh lá cây) có ý nghĩa gì?",
     ["Hiệu ứng xuất hiện của đối tượng lên slide", "Hiệu ứng biến mất đối tượng khỏi slide", "Hiệu ứng nhấn mạnh đối tượng khi đang hiển thị", "Hiệu ứng di chuyển theo đường vẽ"], 0,
     "Entrance (màu xanh) quy định cách đối tượng bay vào hoặc hiện ra."),
    ("Nhóm hiệu ứng Animation 'Emphasis' (màu vàng) có công dụng gì?",
     ["Tạo điểm nhấn, thay đổi kích thước, màu sắc khi đối tượng đang hiển thị trên slide", "Làm đối tượng biến mất", "Làm đối tượng xuất hiện", "Tự động xóa đối tượng"], 0,
     "Emphasis (màu vàng) tạo hiệu ứng nhấn mạnh sự chú ý của người xem."),
    ("Nhóm hiệu ứng Animation 'Exit' (màu đỏ) có tác dụng gì?",
     ["Làm cho đối tượng biến mất khỏi slide khi kích hoạt", "Làm đối tượng xuất hiện", "Làm đối tượng phóng to", "Chuyển sang slide tiếp theo"], 0,
     "Exit (màu đỏ) tạo hiệu ứng đối tượng mờ dần hoặc bay ra ngoài slide."),
    ("Nhóm hiệu ứng 'Motion Paths' trong Animation dùng để làm gì?",
     ["Cho phép đối tượng chuyển động theo một đường dẫn hoặc quỹ đạo tự vẽ", "Đổi màu nền slide", "Xoay đối tượng tại chỗ", "Làm đối tượng nhấp nháy"], 0,
     "Motion Paths cho phép thiết lập đường chuyển động tùy biến cho vật thể."),
    ("Cửa sổ 'Animation Pane' trong PowerPoint giúp người dùng làm gì?",
     ["Xem danh sách, thứ tự và tinh chỉnh thời gian thực thi của các hiệu ứng trên slide", "Vẽ các hình khối mới", "Xem trước toàn bộ các slide ở dạng thu nhỏ", "Ghi âm giọng nói thuyết trình"], 0,
     "Animation Pane quản lý chi tiết danh sách và thứ tự chạy hiệu ứng."),
    ("Tùy chọn kích hoạt hiệu ứng 'On Click' có nghĩa là gì?",
     ["Hiệu ứng chỉ chạy khi người thuyết trình nhấp chuột hoặc nhấn phím", "Hiệu ứng tự động chạy cùng lúc với hiệu ứng trước", "Hiệu ứng tự động chạy ngay sau khi hiệu ứng trước kết thúc", "Hiệu ứng lặp lại vô tận"], 0,
     "On Click yêu cầu thao tác nhấp chuột hoặc phím Space/Enter để bắt đầu."),
    ("Tùy chọn kích hoạt hiệu ứng 'With Previous' có ý nghĩa gì?",
     ["Hiệu ứng chạy đồng thời cùng lúc với hiệu ứng ngay trước đó", "Chạy sau khi nhấp chuột 3 giây", "Chạy khi kết thúc toàn bộ slide", "Chạy sau khi hiệu ứng trước hoàn tất"], 0,
     "With Previous kích hoạt hiệu ứng song song với hành động trước."),
    ("Tùy chọn kích hoạt hiệu ứng 'After Previous' có ý nghĩa gì?",
     ["Hiệu ứng tự động chạy ngay sau khi hiệu ứng liền trước hoàn thành", "Hiệu ứng chạy cùng lúc", "Đợi người dùng nhấp chuột", "Chỉ chạy khi ấn phím Esc"], 0,
     "After Previous tạo chuỗi hoạt họa tự động liên tiếp."),
    ("Công cụ 'Slide Master' trong PowerPoint nằm ở thẻ nào trên thanh Ribbon?",
     ["View -> Slide Master", "Insert -> Slide Master", "Design -> Slide Master", "Review -> Slide Master"], 0,
     "Slide Master nằm trong thẻ View, dùng để thiết lập bố cục và định dạng chuẩn dùng chung cho toàn bộ slide."),
    ("Mục đích chính của việc sử dụng 'Slide Master' là gì?",
     ["Định dạng đồng bộ màu sắc, logo, phông chữ cho toàn bộ các slide một cách nhanh chóng", "Tự động thuyết trình bài giảng bằng giọng đọc AI", "Kiểm tra lỗi chính tả toàn bài", "Chuyển bài thuyết trình thành video"], 0,
     "Mọi thay đổi trên Slide Master sẽ tự động áp dụng cho các slide con trong bài."),
    ("Chế độ xem 'Slide Sorter' trong PowerPoint dùng để làm gì?",
     ["Hiển thị tất cả các slide dưới dạng lưới thu nhỏ để dễ dàng sắp xếp lại thứ tự slide", "Chiếu slide toàn màn hình", "Xem trang ghi chú của người thuyết trình", "Soạn thảo văn bản thuần túy không có hình ảnh"], 0,
     "Slide Sorter hiển thị dàn trang dạng lưới giúp kéo thả thay đổi vị trí slide thuận tiện."),
    ("Để chèn thêm một đoạn âm thanh hoặc video vào slide thuyết trình, ta vào thẻ nào?",
     ["Insert -> Media (Audio / Video)", "Home -> Media", "Design -> Media", "Transitions -> Media"], 0,
     "Thẻ Insert chứa nhóm Media để nhúng âm thanh và video clip."),
    ("Khi đang trình chiếu, muốn chuyển sang một màn hình ĐEN TUYỀN (Black Screen) để thu hút sự chú ý vào người nói, ta nhấn phím:",
     ["Phím B (hoặc dấu chấm .)", "Phím W", "Phím Enter", "Phím Tab"], 0,
     "Bấm phím 'B' (Black) tạm thời biến màn hình thành màu đen; bấm lại để tiếp tục."),
    ("Khi đang trình chiếu, muốn chuyển sang một màn hình TRẮNG TINH (White Screen), ta nhấn phím nào?",
     ["Phím W (hoặc dấu phẩy ,)", "Phím B", "Phím Spacebar", "Phím Shift"], 0,
     "Bấm phím 'W' (White) chuyển màn hình chiếu sang màu trắng."),
    ("Để biến con trỏ chuột thành cây bút vẽ (Pen) để viết vẽ trực tiếp lên slide khi đang thuyết trình, ta nhấn tổ hợp phím:",
     ["Ctrl + P", "Ctrl + A", "Ctrl + E", "Ctrl + H"], 0,
     "Ctrl + P kích hoạt chế độ Pen để vẽ trực tiếp trên màn hình chiếu."),
    ("Để chuyển con trỏ chuột quay trở lại dạng mũi tên thông thường khi đang ở chế độ bút vẽ, ta nhấn:",
     ["Ctrl + A", "Ctrl + P", "Ctrl + E", "Ctrl + L"], 0,
     "Ctrl + A (Arrow) chuyển con trỏ bút vẽ về dạng mũi tên mặc định."),
    ("Để xóa các nét vẽ vừa viết trên màn hình chiếu, ta nhấn phím nào?",
     ["Phím E (Erase)", "Phím D", "Phím X", "Phím Z"], 0,
     "Phím E (Erase) xóa toàn bộ nét vẽ của bút lông trên màn hình slide hiện tại."),
    ("Chức năng 'Action Button' trong PowerPoint dùng để làm gì?",
     ["Tạo các nút điều hướng tương tác (như Home, Next, Back, End) để chuyển slide hoặc phát âm thanh", "Tạo hiệu ứng chữ chạy", "Vẽ biểu đồ hình khối", "Đổi màu nền của slide"], 0,
     "Action Button là các nút hành động tương tác liên kết trong bài thuyết trình."),
    ("Tính năng 'Hyperlink' (Ctrl + K) trong PowerPoint cho phép liên kết tới đâu?",
     ["Một slide khác trong cùng bài, một tệp tin khác, hoặc một trang web", "Chỉ liên kết tới trang web ngoài", "Chỉ liên kết tới slide đầu tiên", "Chỉ liên kết tới hộp thư email"], 0,
     "Hyperlink tạo liên kết linh hoạt tới nội bộ file hoặc tài nguyên bên ngoài."),
    ("Để bài thuyết trình tự động lặp lại liên tục từ đầu khi chiếu đến slide cuối cùng (Kiosk mode), ta thiết lập ở đâu?",
     ["Slide Show -> Set Up Slide Show -> chọn 'Loop continuously until Esc'", "Transitions -> Apply To All", "Design -> Page Setup", "View -> Loop Slide"], 0,
     "Tùy chọn 'Loop continuously until Esc' giúp bài chiếu tự quay vòng liên tục."),
    ("Chế độ 'Presenter View' khi kết nối với máy chiếu có lợi ích gì cho người thuyết trình?",
     ["Người nói thấy được slide tiếp theo, ghi chú bí mật và đồng hồ đếm giờ, trong khi khán giả chỉ thấy slide chính", "Chiếu hai slide khác nhau cùng lúc lên hai màn hình cho khán giả", "Tự động phát âm thanh thuyết trình", "Khóa máy tính không cho ai chỉnh sửa"], 0,
     "Presenter View hỗ trợ đắc lực người nói theo dõi thời gian và nội dung bài."),
    ("Để thiết lập một hiệu ứng chuyển trang (Transition) áp dụng đồng loạt cho TẤT CẢ các slide trong bài, ta nhấn nút nào?",
     ["Apply To All (trong thẻ Transitions)", "Select All Slides", "Copy Transition", "Auto Apply"], 0,
     "Nút 'Apply to All' sao chép cài đặt hiệu ứng chuyển trang hiện tại cho toàn bộ các slide."),
    ("Thẻ nào trên thanh Ribbon dùng để ghi âm giọng nói và quay video màn hình bài thuyết trình?",
     ["Recording (hoặc Insert -> Screen Recording)", "Home", "Design", "Review"], 0,
     "Thẻ Recording cung cấp các công cụ ghi hình và ghi âm bài giảng."),
    ("Để ẩn một slide không cho hiển thị khi trình chiếu mà không cần xóa nó khỏi bài, ta chọn lệnh:",
     ["Hide Slide (trong thẻ Slide Show hoặc nhấp chuột phải)", "Delete Slide", "Disable Slide", "Lock Slide"], 0,
     "Hide Slide ẩn slide khỏi buổi chiếu nhưng vẫn giữ trong file soạn thảo."),
    ("Muốn thay đổi tỷ lệ khung hình của bài thuyết trình giữa chuẩn màn hình rộng 16:9 và chuẩn 4:3, ta vào:",
     ["Design -> Slide Size", "View -> Zoom", "Layout -> Orientation", "Transitions -> Aspect Ratio"], 0,
     "Design -> Slide Size cho phép chọn chuẩn 16:9 Widescreen hoặc 4:3 Standard."),
    ("Công cụ 'Rehearse Timings' trong thẻ Slide Show dùng để làm gì?",
     ["Tập dượt thuyết trình và tự động ghi lại thời gian trình chiếu cho từng slide", "Đếm ngược thời gian tắt máy chiếu", "Tự động đổi hiệu ứng ngẫu nhiên", "Kiểm tra chất lượng âm thanh loa"], 0,
     "Rehearse Timings giúp người nói đo lường thời gian nói trên mỗi slide để tự động chuyển trang."),
    ("Khi muốn xuất bài thuyết trình thành một đoạn video định dạng .mp4, ta vào:",
     ["File -> Export -> Create a Video", "Insert -> Video", "Slide Show -> Export Video", "Home -> Save As Video"], 0,
     "File -> Export -> Create a Video chuyển bài slide kèm hiệu ứng và âm thanh thành video clip."),
    ("Phần mở rộng .PPSX của PowerPoint có đặc điểm gì khi nhấp đúp chuột mở file?",
     ["Tự động mở trực tiếp ở chế độ trình chiếu toàn màn hình (Show mode) mà không vào màn hình soạn thảo", "Là tệp mẫu chỉ đọc", "Là tệp video", "Là tệp đã bị khóa mật khẩu"], 0,
     ".ppsx (PowerPoint Show) lập tức chạy slide show khi mở."),
    ("Để vẽ các hình sơ đồ quy trình thông minh (Hierarchy, Process, Cycle) trên slide, ta dùng công cụ:",
     ["SmartArt (trong thẻ Insert)", "WordArt", "ClipArt", "Photo Album"], 0,
     "SmartArt cung cấp các mẫu biểu đồ quy trình trực quan có sẵn."),
    ("Để chèn chữ nghệ thuật uốn lượn có đổ bóng và viền màu nổi bật vào slide, ta dùng công cụ:",
     ["WordArt (trong thẻ Insert)", "SmartArt", "Shapes", "Text Box"], 0,
     "WordArt tạo chữ nghệ thuật trang trí tiêu đề."),
    ("Để nhóm (Group) nhiều hình vẽ hoặc đối tượng rời rạc thành một khối thống nhất, ta chọn các đối tượng rồi nhấn:",
     ["Ctrl + G", "Ctrl + H", "Ctrl + Shift + G", "Alt + G"], 0,
     "Ctrl + G (Group) nhóm các đối tượng thành một khối duy nhất."),
    ("Để rã nhóm (Ungroup) các đối tượng đã được group trước đó, ta dùng tổ hợp phím:",
     ["Ctrl + Shift + G", "Ctrl + G", "Ctrl + Alt + G", "Shift + G"], 0,
     "Ctrl + Shift + G rã nhóm các đối tượng trở về trạng thái độc lập."),
    ("Khi chèn một bảng số liệu (Table) vào slide, hai thẻ ngữ cảnh nào sẽ xuất hiện trên thanh Ribbon?",
     ["Table Design và Layout", "Format và View", "Data và Tools", "Table Home và Insert"], 0,
     "Khi chọn Table, thẻ Table Design và Layout hiển thị các công cụ chỉnh bảng."),
    ("Trong hộp thoại Animation, thuộc tính 'Duration' có ý nghĩa gì?",
     ["Thời gian kéo dài diễn ra hiệu ứng từ lúc bắt đầu đến khi kết thúc", "Thời gian trì hoãn trước khi hiệu ứng chạy", "Số lần lặp lại hiệu ứng", "Vận tốc của âm thanh đi kèm"], 0,
     "Duration xác định độ dài thời gian thực hiện hiệu ứng (ví dụ: 0.5 giây, 2 giây)."),
    ("Thuộc tính 'Delay' trong hộp thoại Animation có ý nghĩa gì?",
     ["Khoảng thời gian chờ (trì hoãn) trước khi hiệu ứng chính thức bắt đầu chạy", "Thời gian hiệu ứng chạy", "Thời gian tự động tắt slide", "Độ trễ của mạng internet"], 0,
     "Delay tạo khoảng thời gian trễ trước khi hiệu ứng được kích hoạt."),
    ("Muốn in bài thuyết trình với mỗi trang giấy in gồm 3 hoặc 6 slide thu nhỏ có dòng kẻ ghi chú bên cạnh, ta chọn kiểu in nào?",
     ["Handouts", "Full Page Slides", "Notes Pages", "Outline"], 0,
     "Handouts in nhiều slide thu nhỏ trên 1 mặt giấy để phát tài liệu cho thính giả."),
    ("Tính năng 'Notes' ở góc dưới mỗi slide dùng để làm gì?",
     ["Ghi chép các lời thoại hoặc lưu ý cho người thuyết trình xem (không hiện lên màn chiếu chính)", "Trang trí slide bằng các nét chữ viết tay", "Tự động dịch ngôn ngữ", "Đặt mật khẩu bảo vệ slide"], 0,
     "Notes là phần ghi chú dành riêng cho diễn giả chuẩn bị nội dung phát biểu."),
    ("Để căn giữa đối tượng (hình vẽ, khung chữ) vào chính giữa trang slide theo chiều ngang, ta chọn:",
     ["Align -> Align Center", "Align -> Align Middle", "Align -> Align Left", "Align -> Distribute Horizontally"], 0,
     "Align Center căn đối tượng vào tâm trục dọc của trang slide."),
    ("Để thay đổi bố cục sắp xếp các khung tiêu đề và nội dung trên slide hiện hành, ta vào thẻ Home và chọn:",
     ["Layout", "New Slide", "Reset", "Section"], 0,
     "Lệnh Layout trên thẻ Home cho phép thay đổi cấu trúc khung (Title, Two Content, Comparison...).")
]

for q_text, opts, ans, exp in m5_data:
    questions.append({
        "id": len(questions) + 1,
        "module": 5,
        "moduleName": modules_info[5],
        "question": q_text,
        "options": opts,
        "answer": ans,
        "explanation": exp
    })

# Module 6: Sử dụng Internet cơ bản (IU06) - 50 questions
m6_data = [
    ("Thuật ngữ 'WWW' trong địa chỉ các trang web là viết tắt của cụm từ tiếng Anh nào?",
     ["World Wide Web", "World Wide Windows", "World Wide Wire", "World Width Web"], 0,
     "WWW là mạng lưới toàn cầu liên kết các tài liệu siêu văn bản trên Internet."),
    ("Giao thức nào sau đây được sử dụng để truyền tải các trang siêu văn bản an toàn có mã hóa trên Internet?",
     ["HTTPS (Hypertext Transfer Protocol Secure)", "HTTP", "FTP", "SMTP"], 0,
     "HTTPS là giao thức truyền tải siêu văn bản có bảo mật mã hóa qua SSL/TLS."),
    ("Ứng dụng nào sau đây được gọi là một TRÌNH DUYỆT WEB (Web Browser)?",
     ["Google Chrome / Microsoft Edge / Mozilla Firefox", "Microsoft Word", "Windows Media Player", "Adobe Acrobat Reader"], 0,
     "Chrome, Edge, Firefox, Safari là các trình duyệt web phổ biến dùng để truy cập website."),
    ("Địa chỉ URL (Uniform Resource Locator) của một website có ý nghĩa là gì?",
     ["Đường dẫn địa chỉ định danh duy nhất của một tài nguyên trên Internet", "Mật khẩu để đăng nhập vào trang web", "Mã số định danh của máy tính người dùng", "Tên của công ty quản lý mạng viễn thông"], 0,
     "URL là địa chỉ web chỉ dẫn chính xác vị trí tài nguyên trên mạng."),
    ("Trong địa chỉ 'https://www.hcmut.edu.vn', phần '.edu' cho biết website này thuộc lĩnh vực nào?",
     ["Giáo dục và đào tạo (Education)", "Thương mại kinh doanh (Commercial)", "Tổ chức phi lợi nhuận (Organization)", "Cơ quan chính phủ (Government)"], 0,
     ".edu là tên miền cấp cao dành riêng cho các cơ sở giáo dục, trường đại học."),
    ("Tên miền '.gov' (ví dụ: chinhphu.vn hoặc gov.vn) thường dành riêng cho loại hình tổ chức nào?",
     ["Cơ quan nhà nước, chính phủ (Government)", "Doanh nghiệp thương mại", "Tổ chức quân sự", "Cá nhân kinh doanh"], 0,
     ".gov biểu thị trang web chính thức của cơ quan chính phủ."),
    ("Tổ hợp phím tắt nào dùng để mở một Tab (thẻ) mới trong trình duyệt web?",
     ["Ctrl + T", "Ctrl + N", "Ctrl + W", "Ctrl + Shift + T"], 0,
     "Ctrl + T (Tab) mở một tab duyệt web mới."),
    ("Để mở lại Tab vừa mới vô tình đóng trên trình duyệt web, ta dùng tổ hợp phím nào?",
     ["Ctrl + Shift + T", "Ctrl + Shift + N", "Ctrl + Z", "Ctrl + Alt + T"], 0,
     "Ctrl + Shift + T khôi phục lại các tab vừa đóng theo thứ tự."),
    ("Để mở một cửa sổ duyệt web riêng tư (Ẩn danh / Incognito mode) trong Google Chrome, ta nhấn:",
     ["Ctrl + Shift + N", "Ctrl + Shift + P", "Ctrl + N", "Ctrl + Alt + N"], 0,
     "Ctrl + Shift + N mở cửa sổ ẩn danh không lưu lại lịch sử duyệt web."),
    ("Khi sử dụng chế độ duyệt web ẩn danh (Incognito), điều gì sau đây là ĐÚNG?",
     ["Trình duyệt không lưu lịch sử duyệt web, cookie và dữ liệu trang sau khi đóng cửa sổ", "Nhà mạng (ISP) và quản trị mạng hoàn toàn không thể theo dõi bạn", "Bạn được miễn trừ khỏi mọi quy định an ninh mạng", "Máy tính được tự động bảo vệ khỏi mọi loại virus"], 0,
     "Duyệt ẩn danh chỉ xóa lịch sử cục bộ trên máy tính cá nhân khi tắt cửa sổ."),
    ("Tổ hợp phím 'Ctrl + H' trong trình duyệt web dùng để mở tính năng nào?",
     ["Lịch sử duyệt web (History)", "Danh sách dấu trang (Bookmarks)", "Danh sách tệp đã tải xuống (Downloads)", "Công cụ tìm kiếm nâng cao"], 0,
     "Ctrl + H (History) mở danh sách các trang web đã truy cập trong quá khứ."),
    ("Tổ hợp phím 'Ctrl + J' trong trình duyệt web dùng để mở:",
     ["Danh sách các tệp tin đã tải về máy (Downloads)", "Lịch sử duyệt web", "Cửa sổ in trang web", "Mã nguồn trang web"], 0,
     "Ctrl + J mở nhanh trình quản lý tệp tải xuống (Downloads)."),
    ("Để lưu dấu một trang web yêu thích (Bookmark) vào trình duyệt để tiện mở lại sau này, ta dùng phím tắt:",
     ["Ctrl + D", "Ctrl + B", "Ctrl + S", "Ctrl + K"], 0,
     "Ctrl + D (Bookmark/Favorite) lưu trang web hiện tại vào thanh dấu trang."),
    ("Công cụ tìm kiếm (Search Engine) phổ biến nhất hiện nay là gì?",
     ["Google Search / Bing / Yahoo", "Microsoft Word", "Windows Explorer", "Google Drive"], 0,
     "Google, Bing là các cỗ máy tìm kiếm dữ liệu trên Internet."),
    ("Để tìm kiếm một cụm từ CHÍNH XÁC TUYỆT ĐỐI trên Google, ta nên đặt cụm từ đó trong ký tự nào?",
     ["Đặt trong cặp dấu ngoặc kép \"...\"", "Đặt trong cặp dấu ngoặc đơn (...)", "Đặt sau dấu chấm hỏi ?", "Đặt trong cặp dấu hoa thị *...*"], 0,
     "Tìm kiếm với dấu ngoặc kép ép Google tìm đúng nguyên văn thứ tự từ trong ngoặc."),
    ("Để tìm kiếm các tài liệu có định dạng cụ thể (ví dụ file PDF) trên Google, ta dùng cú pháp nào?",
     ["filetype:pdf (ví dụ: giao trinh tin hoc filetype:pdf)", "format:pdf", "type:pdf", "ext=pdf"], 0,
     "Toán tử 'filetype:' lọc kết quả theo đúng đuôi mở rộng của tệp."),
    ("Để giới hạn phạm vi tìm kiếm chỉ trên một website cụ thể (ví dụ trang vnexpress.net), ta dùng toán tử:",
     ["site:vnexpress.net", "web:vnexpress.net", "in:vnexpress.net", "domain=vnexpress.net"], 0,
     "Toán tử 'site:' chỉ định công cụ tìm kiếm chỉ quét nội dung của website đó."),
    ("Cookie trên trình duyệt web có công dụng chính là gì?",
     ["Lưu trữ các thông tin phiên đăng nhập, tùy chọn và trạng thái người dùng trên trang web", "Quét virus cho các trang web", "Tăng tốc độ xử lý phần cứng đồ họa", "Xóa toàn bộ lịch sử truy cập sau 1 giờ"], 0,
     "Cookie là tệp nhỏ ghi nhớ thông tin đăng nhập, giỏ hàng, tùy chỉnh trang web."),
    ("Bộ nhớ đệm (Cache) của trình duyệt web có tác dụng gì?",
     ["Lưu tạm các hình ảnh, nội dung web để tải trang nhanh hơn trong những lần truy cập sau", "Lưu trữ mật khẩu vĩnh viễn", "Bảo vệ máy tính khỏi hacker", "Chặn các quảng cáo rác trên web"], 0,
     "Cache lưu tạm file tĩnh giúp giảm thời gian tải và tiết kiệm băng thông."),
    ("Giao thức nào sau đây chuyên dùng để gửi thư điện tử (Send email) giữa các máy chủ thư?",
     ["SMTP (Simple Mail Transfer Protocol)", "POP3", "IMAP", "HTTP"], 0,
     "SMTP là giao thức chuẩn để gửi thư đi."),
    ("Hai giao thức phổ biến dùng để nhận thư điện tử (Receive email) về ứng dụng hòm thư là:",
     ["POP3 và IMAP", "SMTP và FTP", "HTTP và DNS", "TCP và UDP"], 0,
     "POP3 tải thư về máy cục bộ, IMAP đồng bộ thư trực tiếp với máy chủ hòm thư."),
    ("Cấu trúc một địa chỉ email tiêu chuẩn gồm có những phần nào?",
     ["<Tên_người_dùng> @ <Tên_miền_máy_chủ> (ví dụ: sinhvien@hcmut.edu.vn)", "<Tên_người_dùng> . <Tên_miền>", "http:// <Tên_người_dùng>", "<Tên_người_dùng> # <Mật_khẩu>"], 0,
     "Ký tự @ (at) phân tách giữa tên tài khoản cá nhân và tên miền dịch vụ thư."),
    ("Trong khi gửi email, trường 'CC' (Carbon Copy) có ý nghĩa gì?",
     ["Gửi bản sao thư cho người khác, mọi người nhận đều thấy danh sách địa chỉ của nhau", "Gửi bản sao bí mật không cho ai biết", "Chỉ gửi cho người nhận chính", "Hủy gửi bức thư"], 0,
     "CC gửi đồng kính gửi công khai cho nhiều người cùng theo dõi."),
    ("Trong khi gửi email, trường 'BCC' (Blind Carbon Copy) có ý nghĩa gì?",
     ["Gửi bản sao bí mật, những người nhận khác trong danh sách sẽ KHÔNG thấy được địa chỉ người này", "Gửi bản sao công khai cho tất cả", "Đính kèm tệp tin dung lượng lớn", "Mã hóa nội dung bức thư"], 0,
     "BCC bảo mật danh sách người nhận, không làm lộ email của nhau."),
    ("Hành động 'Spam Email' gây tác hại nào sau đây?",
     ["Làm nghẽn hộp thư, lãng phí thời gian lọc thư và tiềm ẩn nguy cơ chứa mã độc/lừa đảo", "Tự động xóa danh bạ người dùng", "Hỏng phần cứng máy tính", "Tăng tốc độ truyền tải mạng"], 0,
     "Spam email gây phiền toái, quá tải hệ thống và thường mang theo link lừa đảo."),
    ("Để gửi kèm một tệp tài liệu văn bản hoặc hình ảnh cùng với email, ta sử dụng tính năng nào?",
     ["Đính kèm tệp (Attach file - biểu tượng chiếc kẹp giấy)", "Chèn liên kết Hyperlink", "Chụp ảnh màn hình", "Gõ tên tệp vào tiêu đề thư"], 0,
     "Biểu tượng chiếc kẹp ghim (Attachment) cho phép tải file đính kèm gửi cùng thư."),
    ("Dịch vụ lưu trữ và chia sẻ tệp tin trực tuyến của Google có tên là gì?",
     ["Google Drive", "Google Chrome", "Google Maps", "Google Meet"], 0,
     "Google Drive cung cấp không gian lưu trữ đám mây và chia sẻ tài liệu trực tuyến."),
    ("Dịch vụ lưu trữ đám mây tích hợp sẵn trên hệ điều hành Windows của Microsoft là gì?",
     ["Microsoft OneDrive", "iCloud", "Dropbox", "Google Drive"], 0,
     "OneDrive là dịch vụ đám mây đồng bộ mặc định của Microsoft trên Windows."),
    ("Ứng dụng nào sau đây thường dùng để họp và học tập trực tuyến qua video phổ biến?",
     ["Google Meet / Zoom / Microsoft Teams", "Microsoft Excel", "Notepad", "Paint"], 0,
     "Zoom, Google Meet, Teams là các nền tảng hội nghị truyền hình trực tuyến."),
    ("Khái niệm 'IoT' (Internet of Things - Mạng lưới vạn vật kết nối) đề cập đến điều gì?",
     ["Mạng lưới kết nối các đồ vật, thiết bị thông minh qua Internet để thu thập và trao đổi dữ liệu", "Hệ thống chỉ dành cho máy tính và máy in", "Một loại cáp quang biển mới", "Trò chơi giải trí trực tuyến"], 0,
     "IoT kết nối các thiết bị thông minh như đèn, điều hòa, camera, xe hơi vào Internet."),
    ("Mạng xã hội nào sau đây được sử dụng phổ biến nhất để kết nối bạn bè và chia sẻ thông tin?",
     ["Facebook / Instagram / X (Twitter)", "Wikipedia", "Google Scholar", "FileZilla"], 0,
     "Facebook, Instagram là các mạng xã hội chia sẻ trạng thái, hình ảnh cá nhân."),
    ("Khi nhận được một email từ một địa chỉ lạ yêu cầu cung cấp mật khẩu ngân hàng gấp, bạn nên làm gì?",
     ["Tuyệt đối không cung cấp thông tin, báo cáo thư rác hoặc xóa thư ngay", "Gửi ngay mật khẩu để tránh bị khóa thẻ", "Nhấp vào các đường link trong thư để kiểm tra", "Chuyển tiếp thư cho tất cả bạn bè"], 0,
     "Các tổ chức uy tín không bao giờ yêu cầu gửi mật khẩu qua email; đây là dấu hiệu lừa đảo Phishing."),
    ("Tường lửa cá nhân (Personal Firewall) trên máy tính kết nối Internet giúp ích gì?",
     ["Chặn các truy cập trái phép từ bên ngoài mạng vào máy tính và cảnh báo lưu lượng nghi vấn", "Làm máy tính chạy nhanh hơn", "Tự động tải các bộ phim chất lượng cao", "Ngăn bụi bẩn rơi vào phần cứng"], 0,
     "Firewall giám sát các luồng dữ liệu mạng để bảo vệ hệ thống trước sự tấn công từ xa."),
    ("Khi sử dụng mạng Wi-Fi công cộng ở quán cà phê, sân bay, hành vi nào sau đây là KHÔNG AN TOÀN?",
     ["Thực hiện giao dịch chuyển tiền trực tuyến hoặc đăng nhập tài khoản ngân hàng không có 2FA", "Đọc tin tức trên các báo chính thống", "Xem video ca nhạc trên YouTube", "Tra cứu từ điển tiếng Anh"], 0,
     "Wi-Fi công cộng dễ bị kẻ xấu bắt gói tin (Sniffing) đánh cắp thông tin thẻ và tài khoản."),
    ("Mạng riêng ảo (VPN - Virtual Private Network) có lợi ích chính là gì?",
     ["Mã hóa lưu lượng truy cập Internet và bảo vệ quyền riêng tư vị trí địa lý của người dùng", "Tăng tốc độ đường truyền lên gấp 10 lần", "Miễn phí toàn bộ cước Internet hàng tháng", "Sửa chữa cáp quang biển bị đứt"], 0,
     "VPN tạo đường hầm mã hóa bảo vệ dữ liệu khi truyền qua mạng Internet công cộng."),
    ("Giao thức DNS (Domain Name System) đóng vai trò gì trên mạng Internet?",
     ["Chuyển đổi tên miền dễ nhớ (như hcmut.edu.vn) thành địa chỉ IP số (như 14.161.42.1) mà máy tính hiểu được", "Gửi email đi khắp thế giới", "Bảo vệ máy tính khỏi virus", "Lưu trữ nội dung trang web"], 0,
     "DNS giống như danh bạ điện thoại của Internet, phân giải tên miền thành địa chỉ IP."),
    ("Thuật ngữ 'Download' (Tải xuống) có nghĩa là gì?",
     ["Truyền dữ liệu từ máy chủ trên mạng về thiết bị máy tính cá nhân của bạn", "Đưa dữ liệu từ máy tính cá nhân lên mạng Internet", "Xóa dữ liệu trên máy tính", "Khởi động lại modem Internet"], 0,
     "Download là quá trình nạp dữ liệu từ máy chủ từ xa về máy cục bộ."),
    ("Thuật ngữ 'Upload' (Tải lên) có nghĩa là gì?",
     ["Truyền dữ liệu từ máy tính cá nhân của bạn lên máy chủ lưu trữ trên mạng", "Tải dữ liệu từ mạng về máy", "Sao chép tệp giữa hai thư mục trong máy", "Nén tệp tin lại"], 0,
     "Upload là quá trình tải tệp từ thiết bị người dùng lên đám mây hoặc máy chủ."),
    ("Đơn vị Mbps khi nói về gói cước đường truyền Internet của nhà mạng có nghĩa là gì?",
     ["Megabit trên giây (Megabits per second)", "Megabyte trên giây (Megabytes per second)", "Mili-bit trên giây", "Megabit trên phút"], 0,
     "Mbps (chữ b thường) là Megabit/giây, đơn vị chuẩn đo tốc độ truyền tải băng thông."),
    ("Một tệp tin có dung lượng 80 Megabyte (MB), tải trên đường truyền có tốc độ 80 Mbps thì mất khoảng bao lâu trong điều kiện lý tưởng?",
     ["Khoảng 8 giây (vì 1 MB = 8 Mb, 80 MB = 640 Mb; 640 / 80 = 8 giây)", "Khoảng 1 giây", "Khoảng 80 giây", "Khoảng 64 giây"], 0,
     "Cần quy đổi Byte sang Bit: 80 MB * 8 = 640 Mb; với tốc độ 80 Mbps mất khoảng 8 giây."),
    ("Để in trực tiếp một trang web đang mở trên trình duyệt, ta nhấn tổ hợp phím:",
     ["Ctrl + P", "Ctrl + S", "Ctrl + I", "Ctrl + W"], 0,
     "Ctrl + P mở hộp thoại in trang web hoặc lưu trang dưới dạng file PDF."),
    ("Để phóng to toàn bộ nội dung của trang web đang xem, ta dùng phím tắt nào?",
     ["Ctrl + dấu cộng (+)", "Ctrl + dấu trừ (-)", "Ctrl + 0", "Ctrl + Shift + Z"], 0,
     "Ctrl + '+' phóng to tỷ lệ zoom của trình duyệt; Ctrl + '-' thu nhỏ; Ctrl + '0' về 100%."),
    ("Tổ hợp phím 'Ctrl + 0' trong trình duyệt web có tác dụng gì?",
     ["Đưa mức thu phóng của trang web về mặc định 100%", "Đóng toàn bộ các tab", "Mở trang chủ Google", "Tắt âm thanh toàn bộ tab"], 0,
     "Ctrl + 0 khôi phục độ phóng to/thu nhỏ về tỷ lệ gốc 100%."),
    ("Khi muốn lưu toàn bộ trang web về máy tính để đọc khi không có mạng (Offline), ta dùng phím tắt:",
     ["Ctrl + S (Save page as)", "Ctrl + W", "Ctrl + D", "Ctrl + Shift + S"], 0,
     "Ctrl + S lưu trang web thành tệp tin HTML kèm tài nguyên hình ảnh trên ổ đĩa."),
    ("Thao tác nhấp chuột giữa (con lăn chuột) vào một đường liên kết trên trang web sẽ làm gì?",
     ["Mở liên kết đó trong một Tab mới ở chế độ nền", "Mở liên kết trong cửa sổ mới", "Lưu liên kết vào bookmark", "Xóa liên kết đó khỏi trang"], 0,
     "Click chuột giữa lên link là phím tắt tiện lợi để mở link trong tab mới."),
    ("Một website bán hàng uy tín thường có chứng chỉ bảo mật với giao thức bắt đầu bằng chữ gì?",
     ["https://", "http://", "ftp://", "file://"], 0,
     "https:// đảm bảo thông tin thanh toán và mật khẩu được mã hóa an toàn."),
    ("Chức năng 'Bookmark Bar' (Thanh dấu trang) trên trình duyệt hiển thị ở đâu?",
     ["Ngay phía dưới thanh địa chỉ URL để nhấp chuột mở nhanh các trang đã lưu", "Ở cạnh đáy màn hình", "Ẩn hoàn toàn trong menu cài đặt", "Chỉ xuất hiện khi tắt mạng"], 0,
     "Thanh Bookmark Bar nằm cố định dưới thanh địa chỉ giúp truy cập trang nhanh."),
    ("Khi muốn xóa lịch sử duyệt web và tệp rác trong Google Chrome, ta dùng phím tắt:",
     ["Ctrl + Shift + Delete", "Ctrl + Shift + Esc", "Ctrl + Alt + Delete", "Shift + Delete"], 0,
     "Ctrl + Shift + Delete mở ngay hộp thoại 'Clear browsing data' để xóa lịch sử, cache và cookie."),
    ("Việc chia sẻ thông tin sai lệch, chưa được kiểm chứng lên mạng xã hội có thể bị xử lý như thế nào?",
     ["Bị xử phạt vi phạm hành chính hoặc xử lý hình sự theo Luật An ninh mạng", "Không bị xử phạt vì mạng xã hội là thế giới ảo tự do", "Chỉ bị nhắc nhở nhẹ nhàng", "Được thưởng vì tăng tương tác"], 0,
     "Luật An ninh mạng quy định xử phạt nghiêm minh đối với hành vi phát tán thông tin giả mạo sai sự thật."),
    ("Để bảo đảm an toàn thông tin cá nhân trên mạng, người dùng nên thực hiện điều nào sau đây?",
     ["Không công khai số CCCD, tài khoản ngân hàng, mật khẩu và hạn chế chia sẻ vị trí riêng tư lên mạng xã hội", "Đăng tải ảnh chụp hai mặt thẻ căn cước công dân lên nhóm công khai", "Dùng ngày tháng năm sinh làm mật khẩu cho dễ nhớ", "Nhấp vào tất cả đường link khuyến mãi nhận quà tặng bất ngờ"], 0,
     "Bảo vệ dữ liệu cá nhân là nguyên tắc quan trọng hàng đầu trong kỷ nguyên số.")
]

for q_text, opts, ans, exp in m6_data:
    questions.append({
        "id": len(questions) + 1,
        "module": 6,
        "moduleName": modules_info[6],
        "question": q_text,
        "options": opts,
        "answer": ans,
        "explanation": exp
    })

print(f"Total questions generated: {len(questions)}")
counts = {}
for q in questions:
    counts[q['module']] = counts.get(q['module'], 0) + 1
print("Counts per module:", counts)

output_file = "d:/WebsiteTracNghiem/js/questions.js"
with open(output_file, "w", encoding="utf-8") as f:
    f.write("// Ngân hàng 300 câu hỏi trắc nghiệm CNTT Cơ bản (Chuẩn 6 Module)\n")
    f.write("// Phân bố: 50 câu/module x 6 module = 300 câu\n")
    f.write("// Đề thi mỗi lần sẽ trích ngẫu nhiên đúng 5 câu từ mỗi module -> 30 câu / 30 phút\n\n")
    f.write("window.DEFAULT_QUESTION_BANK = ")
    json.dump(questions, f, ensure_ascii=False, indent=2)
    f.write(";\n")

print(f"Successfully wrote to {output_file}")
